### ISSUE TITLE
Errors at replaceRecovery and fixPart

### ISSUE THREAD

**Issue by jtthecanadian** [reviveMC74/reviveMC74#1]
Everything went well up to that point. I tried to continue afterward as clockworks seems to be fully working. (Changed the serial number)
```
C:\reviveMC74>python reviveMC74.py replaceRecovery
  replaceRecovery Function:
    adbDev: List of devices attached
xxxx-xxxx-xxxx  recovery



  --adbModeFunc, currentMode: adb, targetMode: adb
    rRf: adb shell resp: - exec '/system/bin/sh' failed: No such file or directory (2) -

    adbDev: List of devices attached
xxxx-xxxx-xxxx  recovery



  --adbModeFunc, currentMode: adb, targetMode: fastboot
    --Changing from adb mode to fastboot mode
    --loop running 'fastboot devices' until we see a device
    --Waiting for reboot 12/12:
    --Waiting for reboot 11/12:
      found device with serial number: xxxx-xxxx-xxxx
  --replaceRecovery partition
    --Writng revovery partition image:  recovery-clockwork-touch-6.0.4.7-mc74v2.img
    flash resp:

    The recovery partition has been updated; the MC74 is going to reboot now.

    --Hold the 'mute' button down.
    --Press enter on this computer.
    --When the cisco/meraki logo appears and the vibrator grunts, release the 'mute' button
    --(The ClockworkRecovery UI should appear on the display.  You need not do anything on
      that display.)



    --Rebooting
in hndExcept
Exception at <module>:573: WindowsError(2, 'The system cannot find the file specified')
 0  <module> 574 reviveMC74.py --
 1  reviveMain 143 reviveMC74.py --
 2  replaceRecoveryFunc 260 reviveMC74.py --
 3  execute 341 C:\reviveMC74\ribou.py --
 4  __init__ 408 C:\Python27\Lib\subprocess.py --
 5  _execute_child 663 C:\Python27\Lib\subprocess.py --
  Locals: to_close, shell, p2cread, errread, startupinfo, close_fds, c2pread, args, executable, errwrite, cwd, self, _close_in_parent, p2cwrite, env, c2pwrite, creationflags, preexec_fn, universal_newlines
Explore exception stk:
ex>
```
Here's the fixPart:
```
C:\reviveMC74>python reviveMC74.py fixPart
  fixPart Function:
    adbDev: List of devices attached
xxxx-xxxx-xxxx  recovery



  --adbModeFunc, currentMode: adb, targetMode: adb
    rRf: adb shell resp: ro.secure=0

  --backup boot partition: /dev/block/platform/sdhci.1/by-name/boot
    0 2048+0 records in
16384+0 records out
8388608 bytes (8.0MB) copied, 0.265425 seconds, 30.1MB/s

    0 /cache/rmcBoot.img: 1 file pulled, 0 skipped. 7.8 MB/s (8388608 bytes in 1.030s)

    0
    -- unpack rmcBoot.img and unpack the ramdisk
      (unpack:  1)
  --fixPartFunc rmcBoot.img to /dev/block/platform/sdhci.1/by-name/boot
    -- edit default.prop to change ro.secure to = 0
in hndExcept
Exception at <module>:573: IOError(2, 'No such file or directory')
 0  <module> 574 reviveMC74.py --
 1  reviveMain 143 reviveMC74.py --
 2  fixPartFunc 325 reviveMC74.py --
 3  readFile 376 C:\reviveMC74\ribou.py --
  Locals: data, fid
Explore exception stk:
ex>
```
Here's the content of the .log file if that can help:
```
20/10/30-22:04:26 
reviveMC74 revive- --------------------------------------------------------------
20/10/30-22:05:23 
reviveMC74 listObjectives- --------------------------------------------------------------
20/10/30-22:05:32 
reviveMC74 checkFiles- --------------------------------------------------------------
20/10/30-22:09:38 
reviveMC74 checkFiles- --------------------------------------------------------------
20/10/30-22:19:32 
reviveMC74 listObjectives- --------------------------------------------------------------
20/10/30-22:20:02 
reviveMC74 checkFiles- --------------------------------------------------------------
20/10/30-22:20:02 {'needed': [], 'checkFiles': True, 'adbMode': None, 'error': []}
20/10/30-22:20:15 
reviveMC74 adbMode- --------------------------------------------------------------
20/10/30-22:24:19 
reviveMC74 listObjectives- --------------------------------------------------------------
20/10/30-22:26:02 
reviveMC74 adbMode- --------------------------------------------------------------
20/10/30-22:27:54 {'needed': [], 'adbMode': 'adb', 'serialNo': 'xxxx-xxxx-xxxx', 'error': []}
20/10/30-22:28:22 
reviveMC74 replaceRecovery- --------------------------------------------------------------
20/10/30-22:28:33 fastboot flash recovery installFiles/recovery-clockwork-touch-6.0.4.7-mc74v2.img
  0 
20/10/30-22:35:08 
reviveMC74 backupPart- --------------------------------------------------------------
20/10/30-22:35:08 adb shell dd if=/dev/block/platform/sdhci.1/by-name/boot of=/cache/rmcBoot.img ibs=4096
  0 2048+0 records in

16384+0 records out

8388608 bytes (8.0MB) copied, 0.263334 seconds, 30.4MB/s


20/10/30-22:35:09 adb pull /cache/rmcBoot.img .
  0 /cache/rmcBoot.img: 1 file pulled, 0 skipped. 7.7 MB/s (8388608 bytes in 1.036s)

20/10/30-22:35:09 adb shell rm /cache/rmcBoot.img
  0 
20/10/30-22:35:09 python installFiles/packBoot.py unpack rmcBoot.img
  1 
20/10/30-22:35:09 bunch(
  adbMode= 'adb',
  needed= [],
  backupBoot= True,
  fixBootPart= True,
  error= [],
  replaceRecovery= True
)
20/10/30-22:35:34 
reviveMC74 fixPart- --------------------------------------------------------------
20/10/30-22:35:35 adb shell dd if=/dev/block/platform/sdhci.1/by-name/boot of=/cache/rmcBoot.img ibs=4096
  0 2048+0 records in

16384+0 records out

8388608 bytes (8.0MB) copied, 0.265645 seconds, 30.1MB/s


20/10/30-22:35:36 adb pull /cache/rmcBoot.img .
  0 /cache/rmcBoot.img: 1 file pulled, 0 skipped. 7.7 MB/s (8388608 bytes in 1.034s)

20/10/30-22:35:36 adb shell rm /cache/rmcBoot.img
  0 
20/10/30-22:35:36 python installFiles/packBoot.py unpack rmcBoot.img
  1 
20/10/30-22:36:52 
reviveMC74 fixPart- --------------------------------------------------------------
20/10/30-22:36:52 adb shell dd if=/dev/block/platform/sdhci.1/by-name/boot of=/cache/rmcBoot.img ibs=4096
  0 2048+0 records in

16384+0 records out

8388608 bytes (8.0MB) copied, 0.265425 seconds, 30.1MB/s


20/10/30-22:36:53 adb pull /cache/rmcBoot.img .
  0 /cache/rmcBoot.img: 1 file pulled, 0 skipped. 7.8 MB/s (8388608 bytes in 1.030s)

20/10/30-22:36:53 adb shell rm /cache/rmcBoot.img
  0 
20/10/30-22:36:54 python installFiles/packBoot.py unpack rmcBoot.img
  1 

```
Let me know if I can help in any other way to help you out!

**Comment by k0derz-alex** [comment]
My error on fixPart it's different ...

[100%] /cache/rmcBoot.img
/cache/rmcBoot.img: 1 file pulled. 6.8 MB/s (8388608 bytes in 1.169s)

    0
    -- unpack rmcBoot.img and unpack the ramdisk
      (unpack:  1)
  --fixPartFunc rmcBoot.img to /dev/block/platform/sdhci.1/by-name/boot
    -- edit default.prop to change ro.secure to = 0
in hndExcept
Exception at <module>:573: IOError(2, 'No such file or directory')
 0  <module> 574 reviveMc74.py --
 1  reviveMain 143 reviveMc74.py --
 2  fixPartFunc 325 reviveMc74.py --
 3  readFile 376 ribou.py --
  Locals: data, fid
Explore exception stk:

**Comment by jtthecanadian** [comment]
I redid the replaceRecovery and everything went well. I still have the exact same error at fixPart.

I'm running Windows 10 build 2004 with Python 2.7.

**Comment by k0derz-alex** [comment]
Ok, but the code that you was written isn't available right now ...

**Comment by k0derz-alex** [comment]
I'm running Kali Linux with the same Python 2.7, and the last update have SyntaxError

# python reviveMc74.py listObjectives
  File "reviveMc74.py", line 323
    return True  # For normal revive, if boot is fixed, skip it
         ^
SyntaxError: invalid syntax

**Comment by jtthecanadian** [comment]
> I'm running Kali Linux with the same Python 2.7, and the last update have SyntaxError
> 
> # python reviveMc74.py listObjectives
> File "reviveMc74.py", line 323
> return True # For normal revive, if boot is fixed, skip it
> ^
> SyntaxError: invalid syntax

There is a missing paranthesis in the script at the line print(", simple adding it back like i did should fix that:
`  if partName=='boot' and fixBootPart and target!=fixPartFunc:
    print("  --skipping fixPart for boot partition, already done")
    return True  # For normal revive, if boot is fixed, skip it
    # If this is an explicit request to fixPart, do it`

**Comment by k0derz-alex** [comment]
I  know  and line 225

    resp, rc = execute("fasttboot reboot")

is only "fastboot" , other issue that i found is "su -c" not exist!

# adb shell
~ # uname -sva
Linux localhost 3.0.31 #1 SMP PREEMPT Thu May 26 13:52:43 PDT 2016 armv7l GNU/Linux
~ # su -c
/sbin/sh: su: not found

but this is not the end :

# adb install -t audTest.apk
adb: error: failed to copy 'audTest.apk' to '/data/local/tmp/audTest.apk': remote No space left on device
audTest.apk: 0 files pushed. 72.0 MB/s (805975 bytes in 0.011s)

the mount point is /dev/block/platform/sdhci.1/by-name/userdata 956.7M 956.7M 8.0K 100% /data

And this i don't have idea how to fix it!

**Comment by jtthecanadian** [comment]
Syntax was corrected and open another issue for the one you mentionned:
I now have these two same results for backupPart and FixPart
`C:\reviveMC74>python reviveMc74.py fixPart
  fixPart Function:
    adbDev: List of devices attached
xxxx-xxxx-xxxx  recovery



  --adbModeFunc, currentMode: adb, targetMode: adb
    rRf: adb shell resp: ro.secure=0

  --backup boot partition: /dev/block/platform/sdhci.1/by-name/boot
    0 /sbin/sh: su: not found

    1 adb: error: remote object '/cache/rmcBoot.img' does not exist

    0 /sbin/sh: su: not found

fixPart failed:

C:\reviveMC74>python reviveMc74.py backupPart
  backupPart Function:
    adbDev: List of devices attached
xxxx-xxxx-xxxx  recovery



  --adbModeFunc, currentMode: adb, targetMode: adb
    rRf: adb shell resp: ro.secure=0

  --backup boot partition: /dev/block/platform/sdhci.1/by-name/boot
    0 /sbin/sh: su: not found

    1 adb: error: remote object '/cache/rmcBoot.img' does not exist

    0 /sbin/sh: su: not found

backupPart failed:

C:\reviveMC74>`

Here's the Log:
`20/10/31-23:17:54 
reviveMC74 backupPart- --------------------------------------------------------------
20/10/31-23:17:54 adb shell su -c dd if=/dev/block/platform/sdhci.1/by-name/boot of=/cache/rmcBoot.img ibs=4096
  0 /sbin/sh: su: not found


20/10/31-23:17:54 adb pull /cache/rmcBoot.img .
  1 adb: error: remote object '/cache/rmcBoot.img' does not exist

20/10/31-23:17:54 adb shell su -c rm /cache/rmcBoot.img
  0 /sbin/sh: su: not found


20/10/31-23:17:54 bunch(
  needed= [],
  replaceRecovery= True,
  adbMode= 'adb',
  fixBootPart= True,
  error= []
)
20/10/31-23:17:55 
reviveMC74 backupPart- --------------------------------------------------------------
20/10/31-23:17:55 adb shell su -c dd if=/dev/block/platform/sdhci.1/by-name/boot of=/cache/rmcBoot.img ibs=4096
  0 /sbin/sh: su: not found


20/10/31-23:17:56 adb pull /cache/rmcBoot.img .
  1 adb: error: remote object '/cache/rmcBoot.img' does not exist

20/10/31-23:17:56 adb shell su -c rm /cache/rmcBoot.img
  0 /sbin/sh: su: not found


20/10/31-23:17:56 bunch(
  needed= [],
  replaceRecovery= True,
  adbMode= 'adb',
  fixBootPart= True,
  error= []
)
20/10/31-23:18:00 
reviveMC74 fixPart- --------------------------------------------------------------
20/10/31-23:18:00 adb shell su -c dd if=/dev/block/platform/sdhci.1/by-name/boot of=/cache/rmcBoot.img ibs=4096
  0 /sbin/sh: su: not found


20/10/31-23:18:01 adb pull /cache/rmcBoot.img .
  1 adb: error: remote object '/cache/rmcBoot.img' does not exist

20/10/31-23:18:01 adb shell su -c rm /cache/rmcBoot.img
  0 /sbin/sh: su: not found


20/10/31-23:18:01 bunch(
  needed= [],
  replaceRecovery= True,
  adbMode= 'adb',
  fixBootPart= True,
  error= []
)
`

**Comment by jtthecanadian** [comment]
Errors changed since Last Update:
`C:\reviveMC74>python reviveMc74.py backupPart
  backupPart Function:
  Executing: 'adb devices'
  'adb devices'  (rc=0)
    |List of devices attached
    |xxxx-xxxx-xxxx     recovery
    |
  Executing: 'fastboot devices'
  'fastboot devices'  (rc=0)


  --adbModeFunc, currentMode: adb, targetMode: adb
  Executing: 'adb shell grep secure default.prop'
  'adb shell grep secure default.prop'  (rc=0)
    |ro.secure=0

--backupPart boot partition: /dev/block/platform/sdhci.1/by-name/boot
  Executing: 'adb shell su -c dd if=/dev/block/platform/sdhci.1/by-name/boot of=/cache/rmcBoot.img ibs=4096'
  'adb shell su -c dd if=/dev/block/platform/sdhci.1/by-name/boot of=/cache/rmcBoot.img ibs=4096'  (rc=0)
    |/sbin/sh: su: not found
  Executing: 'adb pull /cache/rmcBoot.img .'
  'adb pull /cache/rmcBoot.img .'  (rc=1)
    |adb: error: remote object '/cache/rmcBoot.img' does not exist
  Executing: 'adb shell su -c rm /cache/rmcBoot.img'
  'adb shell su -c rm /cache/rmcBoot.img'  (rc=0)
    |/sbin/sh: su: not found
!!Can't find rmcBoot.img after pulling it
backupPart failed:

C:\reviveMC74>python reviveMc74.py fixPart
  fixPart Function:
  Executing: 'adb devices'
  'adb devices'  (rc=0)
    |List of devices attached
    |xxxx-xxxx-xxxx     recovery
    |
  Executing: 'fastboot devices'
  'fastboot devices'  (rc=0)


  --adbModeFunc, currentMode: adb, targetMode: adb
  Executing: 'adb shell grep secure default.prop'
  'adb shell grep secure default.prop'  (rc=0)
    |ro.secure=0

--backupPart boot partition: /dev/block/platform/sdhci.1/by-name/boot
  Executing: 'adb shell su -c dd if=/dev/block/platform/sdhci.1/by-name/boot of=/cache/rmcBoot.img ibs=4096'
  'adb shell su -c dd if=/dev/block/platform/sdhci.1/by-name/boot of=/cache/rmcBoot.img ibs=4096'  (rc=0)
    |/sbin/sh: su: not found
  Executing: 'adb pull /cache/rmcBoot.img .'
  'adb pull /cache/rmcBoot.img .'  (rc=1)
    |adb: error: remote object '/cache/rmcBoot.img' does not exist
  Executing: 'adb shell su -c rm /cache/rmcBoot.img'
  'adb shell su -c rm /cache/rmcBoot.img'  (rc=0)
    |/sbin/sh: su: not found
!!Can't find rmcBoot.img after pulling it
fixPart failed:`

Log File:
`20/11/01-11:47:59 
reviveMC74 listObjectives- --------------------------------------------------------------
20/11/01-11:48:06 
reviveMC74 checkFiles- --------------------------------------------------------------
20/11/01-11:48:06 {'needed': [], 'checkFiles': True, 'adbMode': None, 'error': []}
20/11/01-11:48:14 
reviveMC74 backupPart- --------------------------------------------------------------
20/11/01-11:48:14   'adb devices'  (rc=0)
    |List of devices attached
    |xxxx-xxxx-xxxx	recovery
    |
20/11/01-11:48:14   'fastboot devices'  (rc=0)

20/11/01-11:48:14   'adb shell grep secure default.prop'  (rc=0)
    |ro.secure=0

20/11/01-11:48:14 
--backupPart boot partition: /dev/block/platform/sdhci.1/by-name/boot
20/11/01-11:48:14   'adb shell su -c dd if=/dev/block/platform/sdhci.1/by-name/boot of=/cache/rmcBoot.img ibs=4096'  (rc=0)
    |/sbin/sh: su: not found

20/11/01-11:48:14   'adb pull /cache/rmcBoot.img .'  (rc=1)
    |adb: error: remote object '/cache/rmcBoot.img' does not exist
20/11/01-11:48:14   'adb shell su -c rm /cache/rmcBoot.img'  (rc=0)
    |/sbin/sh: su: not found

20/11/01-11:48:14 !!Can't find rmcBoot.img after pulling it
20/11/01-11:48:14 bunch(
  needed= [],
  replaceRecovery= True,
  adbMode= 'adb',
  fixBootPart= True,
  error= []
)
20/11/01-11:49:08 
reviveMC74 fixPart- --------------------------------------------------------------
20/11/01-11:49:08   'adb devices'  (rc=0)
    |List of devices attached
    |xxxx-xxxx-xxxx	recovery
    |
20/11/01-11:49:08   'fastboot devices'  (rc=0)

20/11/01-11:49:08   'adb shell grep secure default.prop'  (rc=0)
    |ro.secure=0

20/11/01-11:49:08 
--backupPart boot partition: /dev/block/platform/sdhci.1/by-name/boot
20/11/01-11:49:08   'adb shell su -c dd if=/dev/block/platform/sdhci.1/by-name/boot of=/cache/rmcBoot.img ibs=4096'  (rc=0)
    |/sbin/sh: su: not found

20/11/01-11:49:08   'adb pull /cache/rmcBoot.img .'  (rc=1)
    |adb: error: remote object '/cache/rmcBoot.img' does not exist
20/11/01-11:49:08   'adb shell su -c rm /cache/rmcBoot.img'  (rc=0)
    |/sbin/sh: su: not found

20/11/01-11:49:08 !!Can't find rmcBoot.img after pulling it
20/11/01-11:49:08 bunch(
  needed= [],
  replaceRecovery= True,
  adbMode= 'adb',
  fixBootPart= True,
  error= []
)`

**Comment by qwery26** [comment]
Okay, removed the 'su -c' in a couple commands.  Adding that was a incorrect way of fixing that problem I saw.

Please 'git pull' and try again.

The current version has better error logging and so you/I can see what is happening.  In this last log I see that the dd if=/dev/block/platform/sdhci.1/by-name/boot of=/cache/rmcBoot.img' command failed because the 'su' command was not there. Thus the rmcBoot.img was not read to the host.

Sorry about these bugs -- the nature of this code is that it has lots of different paths that depend on the state of the  MC74 and your host machine and environment, so it is impractical to test them all when go hacking around in the code.  Stay tuned for other apologies or excuses for future bugs.
