### ISSUE TITLE
backupPart

### ISSUE THREAD

**Issue by ra-alex** [reviveMC74/reviveMC74#11]
Executing: 'python installFiles/packBoot.py unpack rmcBoot.img'
  'python installFiles/packBoot.py unpack rmcBoot.img'  (rc=0)
    |cwd /root/Desktop/Alex/reviveMC74/rmcBootUnpack
    |unpackbootimg rmcBoot.img: (rc=0) resp:
    |  |BOARD_KERNEL_CMDLINE console=ttyS0,115200n8 androidboot.console=ttyS0 mem=510M
    |  |BOARD_KERNEL_BASE a0000000
    |  |BOARD_PAGE_SIZE 2048
    |packBoot exception: Traceback (most recent call last):
    |  File "installFiles/packBoot.py", line 150, in <module>
    |    unpack(biFn)
    |  File "installFiles/packBoot.py", line 30, in unpack
    |    print("ls "+os.getcwd()+":\n"+listDir(os.getcwd(), False))
    |TypeError: cannot concatenate 'str' and 'list' objects

**Comment by reviveMC74** [comment]
FIxed,   Sorry
