### ISSUE TITLE
Phone won't boot after fixPart

### ISSUE THREAD

**Issue by jtthecanadian** [reviveMC74/reviveMC74#12]
**Alright, so, I can get to recovery and have backups of my rmcBoot.img.
The resulting image from the fixPart script is 4'488 KB.

Here's the process of the fixPart**
C:\reviveMC74>python reviveMc74.py fixPart
  fixPart Function:
  Executing: 'adb devices'
  'adb devices'  (rc=0)
    |List of devices attached
    |Q2AT-K897-ZJWF     recovery
    |
  Executing: 'fastboot devices'
  'fastboot devices'  (rc=0)

  --adbModeFunc, currentMode: adb, targetMode: adb
  Executing: 'adb shell grep secure default.prop'
  'adb shell grep secure default.prop'  (rc=0)
    |ro.secure=0

--backupPart boot partition: /dev/block/platform/sdhci.1/by-name/boot
  Executing: 'adb shell dd if=/dev/block/platform/sdhci.1/by-name/boot of=/cache/rmcBoot.img ibs=4096'
  'adb shell dd if=/dev/block/platform/sdhci.1/by-name/boot of=/cache/rmcBoot.img ibs=4096'  (rc=0)
    |2048+0 records in
    |16384+0 records out
    |8388608 bytes (8.0MB) copied, 0.262505 seconds, 30.5MB/s
  Executing: 'adb shell rm /cache/rmcBoot.img'
  'adb shell rm /cache/rmcBoot.img'  (rc=0)

    -- unpack rmcBoot.img and unpack the ramdisk
  Executing: 'python installFiles/packBoot.py unpack rmcBoot.img'
  'python installFiles/packBoot.py unpack rmcBoot.img'  (rc=0)
    |cwd C:\reviveMC74\rmcBootUnpack
    |unpackbootimg rmcBoot.img: (rc=0) resp:
    |  |BOARD_KERNEL_CMDLINE console=ttyS0,115200n8 androidboot.console=ttyS0 mem=510M
    |  |BOARD_KERNEL_BASE 0x00000000
    |  |BOARD_NAME
    |  |BOARD_PAGE_SIZE 2048
    |  |BOARD_HASH_TYPE sha1
    |  |BOARD_KERNEL_OFFSET 0x00008000
    |  |BOARD_RAMDISK_OFFSET 0x01000000
    |  |BOARD_SECOND_OFFSET 0x00f00000
    |  |BOARD_TAGS_OFFSET 0x00000100
    |  |BOARD_HEADER_VERSION 0
    |ls C:\reviveMC74\rmcBootUnpack:
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-base
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-board
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-cmdline
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-hashtype
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-header_version
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-kernel_offset
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-pagesize
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-ramdisk.gz
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-ramdisk_offset
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-second_offset
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-tags_offset
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-zImage
    |gunzip rmcBoot.img-ramdisk.gz: 0
    |
    |ramdisk 615936 bytes
    |executeErr: 1203 blocks
    |
    |cwd rd C:\reviveMC74\rmcBootRamdisk
    |executeErr: 1203 blocks
    |
    |cpio -i <rmcBoot.img-ramdisk: 0
    |

--fixPartFunc rmcBoot.img to /dev/block/platform/sdhci.1/by-name/boot
  -- edit default.prop to change ro.secure to = 0
  (UIF create sym link from /ssm to /sdcard/ssm)
  (UIF change prompt to be '\n# ' (shorten it))
      ..#
      ..# ADDITIONAL_DEFAULT_PROPERTIES
      ..#
      ..ro.secure=0
      ..ro.allow.mock.location=0
      ..ro.debuggable=1
      ..persist.brcm.log=auto
      ..persist.brcm.cp_crash=auto
      ..persist.brcm.ap_crash=auto
      ..persist.brcm.force_ramdump=0
      ..persist.meraki.usb_debug=1
      ..persist.sys.usb.config=adb
  Executing: 'chmod go-w rmcBootRamdisk/default.prop'
  'chmod go-w rmcBootRamdisk/default.prop'  (rc=0)

  -- repack ramdisk, repack rmcBoot.img
  Executing: 'python installFiles/packBoot.py pack rmcBoot.img'
  'python installFiles/packBoot.py pack rmcBoot.img'  (rc=0)
    |pack: rmcBoot.img
    |    cwd rd C:\reviveMC74\rmcBootRamdisk
    |'charger\ndata\ndefault.prop\ndev\nfstab.capri_me1\ninit\ninit.bcm911130_me1.rc\ninit.brcm.usb.rc\ninit.common.rc\ninit.goldfish.rc\ninit.log.rc\ninit.rc\ninit.trace.rc\ninit.usb.rc\nproc\nres\nres/images\nres/images/charger\nres/images/charger/battery_0.png\nres/images/charger/battery_1.png\nres/images/charger/battery_2.png\nres/images/charger/battery_3.png\nres/images/charger/battery_4.png\nres/images/charger/battery_5.png\nres/images/charger/battery_charge.png\nres/images/charger/battery_fail.png\nsbin\nsbin/adbd\nsbin/ueventd\nsbin/watchdogd\nsys\nsystem\nueventd.bcm911130_me1.rc\nueventd.goldfish.rc\nueventd.rc\n'
    |cpio -o  rc=0, 615936 bytes
    | ramdisk gzipped 0
    |cmd: '['mkbootimg', '--kernel', 'rmcBoot.img-zImage', '--ramdisk', 'rmcBoot.img-ramdisk.gz', '--cmdline', 'console=ttyS0,115200n8 androidboot.console=ttyS0 mem=510M', '--base', '0x0x00000000', '--pagesize', '2048', '--output', '../rmcBoot.img2011032203']'
    |(rc=0) resp:
    |
__|C:\reviveMC74/rmcBoot.img2011032203
__|C:\reviveMC74/rmcBoot.imgOrig
__|C:\reviveMC74/rmcBoot.imgOrig.bak
..|C:\reviveMC74/rmcBoot.img
..|C:\reviveMC74/rmcBoot.imgOrig
..|C:\reviveMC74/rmcBoot.imgOrig.bak
  -- write new rmcBoot.img to boot parition
  Executing: 'adb shell dd if=/cache/rmcBoot.img of=/dev/block/platform/sdhci.1/by-name/boot ibs=4096'
  'adb shell dd if=/cache/rmcBoot.img of=/dev/block/platform/sdhci.1/by-name/boot ibs=4096'  (rc=0)
    |1122+0 records in
    |8976+0 records out
    |4595712 bytes (4.4MB) copied, 0.768479 seconds, 5.7MB/s
  Executing: 'adb shell rm /cache/rmcBoot.img'
  'adb shell rm /cache/rmcBoot.img'  (rc=0)

Acheived objective 'fixPart'

**Here's the log File:**
20/11/03-22:03:00 
reviveMC74 fixPart- --------------------------------------------------------------
20/11/03-22:03:00   'adb devices'  (rc=0)
    |List of devices attached
    |Q2AT-K897-ZJWF	recovery
    |
20/11/03-22:03:00   'fastboot devices'  (rc=0)

20/11/03-22:03:00   'adb shell grep secure default.prop'  (rc=0)
    |ro.secure=0

20/11/03-22:03:00 
--backupPart boot partition: /dev/block/platform/sdhci.1/by-name/boot
20/11/03-22:03:00   'adb shell dd if=/dev/block/platform/sdhci.1/by-name/boot of=/cache/rmcBoot.img ibs=4096'  (rc=0)
    |2048+0 records in

    |16384+0 records out

    |8388608 bytes (8.0MB) copied, 0.262505 seconds, 30.5MB/s

20/11/03-22:03:01   'adb shell rm /cache/rmcBoot.img'  (rc=0)

20/11/03-22:03:01   'python installFiles/packBoot.py unpack rmcBoot.img'  (rc=0)
    |cwd C:\reviveMC74\rmcBootUnpack
    |unpackbootimg rmcBoot.img: (rc=0) resp:
    |  |BOARD_KERNEL_CMDLINE console=ttyS0,115200n8 androidboot.console=ttyS0 mem=510M
    |  |BOARD_KERNEL_BASE 0x00000000
    |  |BOARD_NAME 
    |  |BOARD_PAGE_SIZE 2048
    |  |BOARD_HASH_TYPE sha1
    |  |BOARD_KERNEL_OFFSET 0x00008000
    |  |BOARD_RAMDISK_OFFSET 0x01000000
    |  |BOARD_SECOND_OFFSET 0x00f00000
    |  |BOARD_TAGS_OFFSET 0x00000100
    |  |BOARD_HEADER_VERSION 0
    |ls C:\reviveMC74\rmcBootUnpack:
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-base
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-board
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-cmdline
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-hashtype
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-header_version
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-kernel_offset
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-pagesize
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-ramdisk.gz
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-ramdisk_offset
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-second_offset
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-tags_offset
    |--|C:\reviveMC74\rmcBootUnpack/rmcBoot.img-zImage
    |gunzip rmcBoot.img-ramdisk.gz: 0
    |
    |ramdisk 615936 bytes
    |executeErr: 1203 blocks
    |
    |cwd rd C:\reviveMC74\rmcBootRamdisk
    |executeErr: 1203 blocks
    |
    |cpio -i <rmcBoot.img-ramdisk: 0
    |
20/11/03-22:03:01 
--fixPartFunc rmcBoot.img to /dev/block/platform/sdhci.1/by-name/boot
20/11/03-22:03:01   -- edit default.prop to change ro.secure to = 0
20/11/03-22:03:01   default.prop:
   |#
   |# ADDITIONAL_DEFAULT_PROPERTIES
   |#
   |ro.secure=0
   |ro.allow.mock.location=0
   |ro.debuggable=1
   |persist.brcm.log=auto
   |persist.brcm.cp_crash=auto
   |persist.brcm.ap_crash=auto
   |persist.brcm.force_ramdump=0
   |persist.meraki.usb_debug=1
   |persist.sys.usb.config=adb
20/11/03-22:03:01 itermediate default.prop:
#
# ADDITIONAL_DEFAULT_PROPERTIES
#
ro.secure=0
ro.allow.mock.location=0
ro.debuggable=1
persist.brcm.log=auto
persist.brcm.cp_crash=auto
persist.brcm.ap_crash=auto
persist.brcm.force_ramdump=0
persist.meraki.usb_debug=1
persist.sys.usb.config=adb
20/11/03-22:03:01   'chmod go-w rmcBootRamdisk/default.prop'  (rc=0)

20/11/03-22:03:01     fixed boot default.prop:
#
# ADDITIONAL_DEFAULT_PROPERTIES
#
ro.secure=0
ro.allow.mock.location=0
ro.debuggable=1
persist.brcm.log=auto
persist.brcm.cp_crash=auto
persist.brcm.ap_crash=auto
persist.brcm.force_ramdump=0
persist.meraki.usb_debug=1
persist.sys.usb.config=adb
20/11/03-22:03:01   -- repack ramdisk, repack rmcBoot.img
20/11/03-22:03:02   'python installFiles/packBoot.py pack rmcBoot.img'  (rc=0)
    |pack: rmcBoot.img
    |    cwd rd C:\reviveMC74\rmcBootRamdisk
    |'charger\ndata\ndefault.prop\ndev\nfstab.capri_me1\ninit\ninit.bcm911130_me1.rc\ninit.brcm.usb.rc\ninit.common.rc\ninit.goldfish.rc\ninit.log.rc\ninit.rc\ninit.trace.rc\ninit.usb.rc\nproc\nres\nres/images\nres/images/charger\nres/images/charger/battery_0.png\nres/images/charger/battery_1.png\nres/images/charger/battery_2.png\nres/images/charger/battery_3.png\nres/images/charger/battery_4.png\nres/images/charger/battery_5.png\nres/images/charger/battery_charge.png\nres/images/charger/battery_fail.png\nsbin\nsbin/adbd\nsbin/ueventd\nsbin/watchdogd\nsys\nsystem\nueventd.bcm911130_me1.rc\nueventd.goldfish.rc\nueventd.rc\n'
    |cpio -o  rc=0, 615936 bytes
    | ramdisk gzipped 0
    |cmd: '['mkbootimg', '--kernel', 'rmcBoot.img-zImage', '--ramdisk', 'rmcBoot.img-ramdisk.gz', '--cmdline', 'console=ttyS0,115200n8 androidboot.console=ttyS0 mem=510M', '--base', '0x0x00000000', '--pagesize', '2048', '--output', '../rmcBoot.img2011032203']'
    |(rc=0) resp:
    |
20/11/03-22:03:02 __|C:\reviveMC74/rmcBoot.img2011032203
__|C:\reviveMC74/rmcBoot.imgOrig
__|C:\reviveMC74/rmcBoot.imgOrig.bak
20/11/03-22:03:02 ..|C:\reviveMC74/rmcBoot.img
..|C:\reviveMC74/rmcBoot.imgOrig
..|C:\reviveMC74/rmcBoot.imgOrig.bak
20/11/03-22:03:02   -- write new rmcBoot.img to boot parition
20/11/03-22:03:03   'adb shell dd if=/cache/rmcBoot.img of=/dev/block/platform/sdhci.1/by-name/boot ibs=4096'  (rc=0)
    |1122+0 records in

    |8976+0 records out

    |4595712 bytes (4.4MB) copied, 0.768479 seconds, 5.7MB/s

20/11/03-22:03:03   'adb shell rm /cache/rmcBoot.img'  (rc=0)

20/11/03-22:03:03 bunch(
  adbMode= 'adb',
  needed= [],
  backupBoot= True,
  fixBootPart= True,
  error= [],
  replaceRecovery= True
)

**Comment by reviveMC74** [comment]
What happens when you try to boot the phone?  (ie apply power through the POE ethernet cable, or external power supply)  
Does the screen backlight come on?
Does the 'vibrator' 'grunt' slightly within a few seconds?
Does the Cisco/Meraki logo screen with black background come on?
Does the Cisco/Meraki logo screen with white background come on?
Does that logo screen go away and get replaced by anything?

With the USB-A to USB-A cable connected to host computer and side USB port of MC74, does 'adb devices' show anything?
If you know how to see what wired or wifi devices are on you local network (ie though the web page to your home router), do you see a wired or wifi device that could be the MC74?  (It might have a MAC address of:  E0-55-3D-xx-xx-xx)

Failing all that, can you boot into recovery mode (ie by holding down the mute button while powering on and releasing mute after the 'grunt')  Does the recovery screen show up?

**Comment by jtthecanadian** [comment]
It's stuck at the Cisco Meraki logo. It doesn't vibrate at all when booting normally. The device isn't reachable from the network. It also doesn't show up in the usb connected devices on my computer nor  from ADB (did adb devices and nothing shows up). Tried from both Windows and Ubuntu to be sure.
I can get back to ClockWorkMod Recovery with no issue and still have the original .img file from the backupPart.

**Comment by reviveMC74** [comment]
Do a 'git'pull' to get the lastest code.   I changed the reviveMC74.py script to expose the 'flashPart' objective separately, so any partition image can be written to the device explicitly.   (If you are not restoring the 'boot' partition, add the 'part=XXX' option)
Try:

 python reviveMC74 flashPart img=MYIMGFILE

I assume you didn't change any other partitions.  If that fails, we could try copying the contents of you boot2 partition to boot, or I could send you a partition image I have.

**Comment by jtthecanadian** [comment]
I'm probably gonna need a known working image. It won't work with the one I backed up.
Sorry.

**Comment by jtthecanadian** [comment]
My bad, it worked! One of the images was corrupted.

**Comment by jtthecanadian** [comment]
Hey, so, I tried to the the fixPart again and get the exact same result when I flash the resulting image.
I can always come back to my original image with no issue, but, the fixed partition won't work.
I'm not sure how to help on that issue tho. Let me know what you need to diagnose it. I added the resulting image to my comment.
[rmcBoot.zip](https://github.com/reviveMC74/reviveMC74/files/5503947/rmcBoot.zip)


Here's the Log from the transfer:

20/11/06-18:29:48 
reviveMC74 fixPart- --------------------------------------------------------------
20/11/06-18:29:49   'adb devices'  (rc=0)
    |List of devices attached
    |Q2AT-K897-ZJWF	recovery
    |
20/11/06-18:29:49   'fastboot devices'  (rc=0)

20/11/06-18:29:49   'adb shell grep secure default.prop'  (rc=0)
    |ro.secure=0

20/11/06-18:29:49 
--fixPartFunc rmcBoot.img to make it rooted.
20/11/06-18:29:49   -- edit default.prop to change ro.secure to = 0
20/11/06-18:29:49   default.prop:
   |#
   |# ADDITIONAL_DEFAULT_PROPERTIES
   |#
   |ro.secure=0
   |ro.allow.mock.location=0
   |ro.debuggable=1
   |persist.brcm.log=auto
   |persist.brcm.cp_crash=auto
   |persist.brcm.ap_crash=auto
   |persist.brcm.force_ramdump=0
   |persist.meraki.usb_debug=1
   |persist.sys.usb.config=adb
20/11/06-18:29:49 itermediate default.prop:
#
# ADDITIONAL_DEFAULT_PROPERTIES
#
ro.secure=0
ro.allow.mock.location=0
ro.debuggable=1
persist.brcm.log=auto
persist.brcm.cp_crash=auto
persist.brcm.ap_crash=auto
persist.brcm.force_ramdump=0
persist.meraki.usb_debug=1
persist.sys.usb.config=adb
20/11/06-18:29:49   'chmod go-w rmcBootRamdisk/default.prop'  (rc=0)

20/11/06-18:29:49     fixed boot default.prop:
#
# ADDITIONAL_DEFAULT_PROPERTIES
#
ro.secure=0
ro.allow.mock.location=0
ro.debuggable=1
persist.brcm.log=auto
persist.brcm.cp_crash=auto
persist.brcm.ap_crash=auto
persist.brcm.force_ramdump=0
persist.meraki.usb_debug=1
persist.sys.usb.config=adb
20/11/06-18:29:49   -- repack ramdisk, repack rmcBoot.img
20/11/06-18:29:50   'python installFiles/packBoot.py pack rmcBoot.img'  (rc=0)
    |pack: rmcBoot.img
    |    cwd rd C:\reviveMC74\rmcBootRamdisk
    |'charger\ndata\ndefault.prop\ndev\nfstab.capri_me1\ninit\ninit.bcm911130_me1.rc\ninit.brcm.usb.rc\ninit.common.rc\ninit.goldfish.rc\ninit.log.rc\ninit.rc\ninit.trace.rc\ninit.usb.rc\nproc\nres\nres/images\nres/images/charger\nres/images/charger/battery_0.png\nres/images/charger/battery_1.png\nres/images/charger/battery_2.png\nres/images/charger/battery_3.png\nres/images/charger/battery_4.png\nres/images/charger/battery_5.png\nres/images/charger/battery_charge.png\nres/images/charger/battery_fail.png\nsbin\nsbin/adbd\nsbin/ueventd\nsbin/watchdogd\nsys\nsystem\nueventd.bcm911130_me1.rc\nueventd.goldfish.rc\nueventd.rc\n'
    |cpio -o  rc=0, 615936 bytes
    | ramdisk gzipped 0
    |cmd: '['mkbootimg', '--kernel', 'rmcBoot.img-zImage', '--ramdisk', 'rmcBoot.img-ramdisk.gz', '--cmdline', 'console=ttyS0,115200n8 androidboot.console=ttyS0 mem=510M', '--base', '0x0xa0000000', '--pagesize', '2048', '--output', '../rmcBoot.img2011061829']'
    |(rc=0) resp:
    |
20/11/06-18:29:50 __|C:\reviveMC74/rmcBoot.img2011061829
__|C:\reviveMC74/rmcBoot.imgOrig
20/11/06-18:29:50 ..|C:\reviveMC74/rmcBoot.img
..|C:\reviveMC74/rmcBoot.imgOrig
20/11/06-18:29:50 bunch(
  adbMode= 'adb',
  needed= [],
  backupBoot= True,
  fixBootPart= True,
  error= [],
  replaceRecovery= True
)
20/11/06-18:35:19 
reviveMC74 flashPart-img=rmcBoot.img --------------------------------------------------------------
20/11/06-18:35:19 
--flashPartFunc, writing rmcBoot.img to /dev/block/platform/sdhci.1/by-name/boot
20/11/06-18:35:19   'adb push rmcBoot.img /cache/rmcBoot.img'  (rc=0)
    |rmcBoot.img: 1 file pushed, 0 skipped. 404.0 MB/s (4595712 bytes in 0.011s)
20/11/06-18:35:20   'adb shell dd if=/cache/rmcBoot.img of=/dev/block/platform/sdhci.1/by-name/boot ibs=4096'  (rc=0)
    |1122+0 records in

    |8976+0 records out

    |4595712 bytes (4.4MB) copied, 0.773048 seconds, 5.7MB/s

20/11/06-18:35:20   'adb shell rm /cache/rmcBoot.img'  (rc=0)

20/11/06-18:35:20 {'needed': [], 'adbMode': None, 'fixBootPart': True, 'error': []}`

**Comment by reviveMC74** [comment]
Could you try 'git add'   'git commit' and  'git push' of the rmcBoot.img file and your working original boot img to this repo?    I'll see if I can see a problem.   I haven't found a place where the syslog of the 'normal' boot of the system is stored that we could look at after the fact.

**Comment by jtthecanadian** [comment]
I'm not sure if I did it right, but, the file is in my fork.

**Comment by PhoenixSheppy** [comment]
Yeah, I'm getting a similar experience on my phone as well. I ran backupPart, fixPart, and then flashPart and now it won't boot past the Meraki logo. Odd.

**Comment by reviveMC74** [comment]
I sent PoenixSheppy and jtthecandian boot img I used for them to 'flashPat' to see if that works.  (Also suggested trying to 'flashPart' the their backup versions (rmcBoot.imgOrig) to see if that restore the device to it previous state.

Could you post your MC74 software versions, per: [https://www.reddit.com/r/ReviveMC74/comments/jqz7rp/mc74_software_versions/](https://www.reddit.com/r/ReviveMC74/comments/jqz7rp/mc74_software_versions/) 
so we can see what versions are having problems?

Also I think we need to find the console serial port on the phone's hardware to be able to debug things better.

**Comment by qwery26** [comment]
This should be fixed now (do a  'git pull')    It seems that clockwork recovery hangs when given a reboot request from adb.  (You can reboot by tapping the 'reboot' menu item on the display,)

I used a more primal incantation to get the thing to reboot.
