### ISSUE TITLE
Device Ringer Doesn't go off when called on wPhone / LinPhone.

### ISSUE THREAD

**Issue by PhoenixSheppy** [reviveMC74/reviveMC74#15]
When calling phone w/ LinPhone installed, Device does not ring audibly unless "Use Device Ringtone" in the settings under call is disabled.

Not sure how to grab info on this, but if supplied with information I could probably get it.

**Comment by reviveMC74** [comment]
(This isn't really a reviveMC74 script problem, but...)  The MC74 doesn't have a 'ringer' in the traditional sense, does it?  So you mean the speakerphone speaker doesn't make a sound when there is an incoming call?  Is this the  'revive.MC74.debug' application isntalled by the script or another version of  the Linphone app?  

The Linphone sorce file: main/java/org/linphone/settings/LinphonePreferences.java as this function:

    return getConfig().getBool("app", "device_ringtone", true)

The getConfig() function reads from various files like:  .linphonerc    (note the '.' in the name that makes it a hidden file) in the /data/data/<applicationName>/files directory.  One of those file may have a 'device_ringtone' value.  'device_ringtone' is the property that is set by the 'Use Device Ringtone' entry in settings/CallSettingsFragment.java part  of the 'Settings' activity of Linphone.

**Comment by PhoenixSheppy** [comment]
> (This isn't really a reviveMC74 script problem, but...)  The MC74 doesn't have a 'ringer' in the traditional sense, does it?  So you mean the speakerphone speaker doesn't make a sound when there is an incoming call?  Is this the  'revive.MC74.debug' application isntalled by the script or another version of  the Linphone app?  
> 
> The Linphone sorce file: main/java/org/linphone/settings/LinphonePreferences.java as this function:
> 
>     return getConfig().getBool("app", "device_ringtone", true)
> 
> The getConfig() function reads from various files like:  .linphonerc    (note the '.' in the name that makes it a hidden file) in the /data/data/<applicationName>/files directory.  One of those file may have a 'device_ringtone' value.  'device_ringtone' is the property that is set by the 'Use Device Ringtone' entry in settings/CallSettingsFragment.java part  of the 'Settings' activity of Linphone.
> 

In the settings menu, you can set a ringtone. So technically it does.

Yeah when I call the phone with Linphone running it doesn't make a sound at all.

I'm using the revive debug dialer app, that was included with the GitHub repo.

The only way I've gotten the sound to work is to use the app's ring function.

**Comment by qwery26** [comment]
When a call come in, does the IncomingCallActivity show up (with the button/slider allowing you to answer the call?  This would indicate that the app knows a call is coming in.  I wonder if either the main speaker is not activated, or the 'ringtone' audio file is not there.  (You said you 'disabled' the Use Device Ringtone setting once you do that do you get audio when a call comes in?)

Could you email me the logcat around the time that a call comes  in?

**Comment by PhoenixSheppy** [comment]
Sorry for the late response, yeah, when I call the phone via another SIP phone, the "incoming call" prompt appears and I can pick it up and speak through the handset.

But the ringtone is not present, I can take a logcat real quick and email it to you. One second.

**Comment by PhoenixSheppy** [comment]
Protonmail is down or something because I can't access my inbox at the moment.

I've uploaded my logcat to my CDN, feel free to take a look. Shouldn't be anything sensitive in there.
https://cdn.gsheps.com/mrKrx

**Comment by PhoenixSheppy** [comment]
Okay, if you pick up the phone, switch to speaker, and then hang up and call again the ringtone goes through the handset.

**Comment by reviveMC74** [comment]
I just pushed an updated reviveMC74 package which includes lots of updates, some of which may fix the ringtone problem and the automatic switching between handset and speakerphone speakers,  Pull the latest version.  You could use the usual reviveMC74 update process, or, I think you know how to install .apk files manually.  Install the latest  installFiles/revive.MC74-debug.apk and installFiles/revive.SSMService-debug.apk and reboot the MC74.

There is now an readable/user modifiable config file named: **MC74.mp**, try:

**adb shell cat /sdcard/ssm/store/MC74.mp**

The top of the file should look like:

  TITLE: 'Meraki MC74 Config'
  bg: 'whiteSlate.jpg'
  config:
    screenSaver:
      img: "row.jpg"
      lightSleep: '600'
      deepSleep: '1200'
    ringtone: '/system/media/audio/ringtones/Trad.ogg'
    ringVibrate:
  swipe:
    inRight: 'ribo.ssm.Phone doKeyEvent BACK'
    outLeft: 'ribo.ssm.Phone doKeyEvent BACK'
    inTop: 'ribo.ssm.Phone doKeyEvent HOME'
    inBottom: 'ribo.ssm.Phone doKeyEvent MENU'
  mainFooter: ''
    history: ''
      act: 'org.linphone.history.HistoryActivity'
`
Note the 'ringtone' line in the 'config' section.  That is the name of the audio file to be used for the ring tone. ('ringVibrate' means the vibrator should sound, as well, when  a call comes in. )  You may want to verify that the /system/media/audio/ringtones/Trad.ogg file exists on your phone.

GIve it a try.

**Comment by PhoenixSheppy** [comment]
I've updated my phone, and configured that file, still no ringtone. Also none of the modifications I apply seem to be actually applying. 

I tried changing the wallpaper, the clock background, the ringtone, etc. None of it seems to be actually changing anything.

**Comment by PhoenixSheppy** [comment]
Buuuut on the plus side, the ringtone now works when you change it to the app-based ringtone. And picking up and putting down the handset picks up and hangs up the call now.

**Comment by reviveMC74** [comment]
Oh, for people who used one of the previous versions of the installer, I think you will need to do this:

    adb shell rm /sdcard/ssm/store/MC74.nob

(The MC74 configuration object was in a not directly human readable binary form, in a file:  MC74.nob   The new MC74.mp is a text file that is easier to use.  The system reads the .nob file before (in preference to) the .mp file. )

So, remove that MC74.nob  and reboot, or restart the phone app.

You can verify that the new MC74.mp file was installed with:

    adb shell ls -l /sdcard/ssm/store/MC74*

It should only list MC74.mp

To restart the phone app ('revive.MC74') without needed to reboot:

    adb shell
    am force-stop revive.MC74
    am start revive.MC74/org.linphone.dialer.DialerActivity

**Comment by PhoenixSheppy** [comment]
Perfect!

Removing the file `MC74.nob` resolved the issue entirely!
All customizations are now working, and my ringtone now plays!

Good call! issue resolved.
