### ISSUE TITLE
When picking up handset, dialtone persists into call.

### ISSUE THREAD

**Issue by PhoenixSheppy** [reviveMC74/reviveMC74#19]
To reproduce:
- Pickup handset.
- Dial extension.
- Listen, it keeps playing the dialtone noise even though a call is on-going.

If required, I can obtain a logcat, just let me know.

**Comment by reviveMC74** [comment]
Please send me the logcat.  The code below, in diakter/views/Digit.java   should run in onClick when you click a button to dial a number.  Let's see if the logcat shows the 'Stoping dialtone" msg (I'll fix the spelling in the message) 

>         // WL A button was pressed stop the dialtone if it is playing
>         if (Info.dialtonePlaying) {
>             prt("dialer.views.Digit.onClick: Stoping dialtone.");
>             Info.dialtonePlaying = false;
>             VoicemailAct.mp.stop();
>         }

If that message shows and the dialtone doesn't stop we'll have to see if there is any following message about the MediaPlayer not stopping.

**Comment by qwery26** [comment]
I don't see this occurring these days.  If the problem still exists with the current release, open this issue again
