### ISSUE TITLE
Issue with fixPart

### ISSUE THREAD

**Issue by neodataworks** [reviveMC74/reviveMC74#21]
Hi there, trying to use this MC74 that I've had lying around.  i am running the script and see that it is pulling the rmcBoot.imgOrig and Raw but fails on the fixPart stating the error below:

C:\MC74\reviveMC74>c:\Python27\python.exe reviveMC74.py fixPart
fixPart Function:
fixPartFunc rmcBoot.imgRaw to make it rooted.
  -- edit default.prop to change ro.secure to = 0
  !! Can't find: rmcBootRamdisk/default.prop in C:\MC74\reviveMC74
  !! Rerun the 'fixPart' objective.
fixPart failed:

it creates the folder rmcBootUnpack, but this is empty.  the rest of the script prior to this seems to have worked and the phone is booted to the recovery screen.  ABD sees it of course since it downloaded the files so not sure where i am failing.  i have checked security on the files since i am using windows and this seems OK.  thanks in advance.

**Comment by qwery26** [comment]
Could you attach the reviveMC74.log file?

    print("  --unpack "+imgFn+" and unpack the ramdisk")
    resp, rc = executeLog(sys.executable+' '+installFilesDir+"/packBoot.py unpack "+imgFn)
    # sys.executable is the name of the python interpreter we are running

I'm guessing the above part of the python script failed.  Are you experienced enough to execute a command like:

    python installFiles/packBoot,py unpack rmcBoot.img

from your \MC74\reviveMC74 directory.   Assuming you have a copy of rmcBoot.img in it.
I have been seeing people having problems with the 'unpackbootimg.exe' file downloaded from the internet.  Make sure the that version of 'unpackbootimg' that your system will execute (ie in your %PATH%) is equivalent to the one in the installFiles directory.   Show me the results of the 'packBoot,py unpack' command above.

**Comment by neodataworks** [comment]
thanks for answering.  log is below.

when i try to run "python installFiles/packBoot,py unpack rmcBoot.imgOrig" because i do not have this file without Orig at the end, i get:

C:\MC74\reviveMC74>c:\Python27\python.exe  installFiles\packBoot.py unpack rmcBoot.imgOrig
cwd C:\MC74\reviveMC74\rmcBootUnpack
packBoot exception: Traceback (most recent call last):
  File "installFiles\packBoot.py", line 202, in <module>
    unpack(biFn)
  File "installFiles\packBoot.py", line 30, in unpack
    resp, rc = execute("unpackbootimg -i ../"+biFn)
  File "C:\MC74\reviveMC74\ribou.py", line 375, in execute
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "c:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "c:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified


22/02/16-17:04:04 revive===================================================================
22/02/16-17:04:04 --(reviveFunc)
22/02/16-17:04:04     (rmcBoot.img not found, calling fixPart to create it)
22/02/16-17:04:09     'adb devices'  (rc=0)
      |List of devices attached
      |adb server is out of date.  killing...
      |* daemon started successfully *
      |Q2AT-CBD9-HX32	recovery
      |
22/02/16-17:04:09     'fastboot devices'  (rc=0)

22/02/16-17:04:09   --adbModeFunc, currentMode: recovery, targetMode: adb adb
22/02/16-17:04:09     'adb shell grep secure default.prop'  (rc=0)
      |ro.secure=0

22/02/16-17:04:09     'adb shell id'  (rc=0)
      |uid=0(root) gid=0(root)

22/02/16-17:04:09 backupPart boot partition: /dev/block/platform/sdhci.1/by-name/boot
22/02/16-17:04:09     'adb shell dd if=/dev/block/platform/sdhci.1/by-name/boot of=/cache/rmcBoot.imgRaw ibs=4096'  (rc=0)
      |2048+0 records in

      |16384+0 records out

      |8388608 bytes (8.0MB) copied, 0.262631 seconds, 30.5MB/s

22/02/16-17:04:11     'adb shell rm /cache/rmcBoot.imgRaw'  (rc=0)

22/02/16-17:04:11     'c:\Python27\python.exe installFiles/packBoot.py unpack rmcBoot.imgRaw'  (rc=0)
      |cwd C:\MC74\reviveMC74\rmcBootUnpack
      |packBoot exception: Traceback (most recent call last):
      |  File "installFiles/packBoot.py", line 202, in <module>
      |    unpack(biFn)
      |  File "installFiles/packBoot.py", line 30, in unpack
      |    resp, rc = execute("unpackbootimg -i ../"+biFn)
      |  File "C:\MC74\reviveMC74\ribou.py", line 375, in execute
      |    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      |  File "c:\Python27\lib\subprocess.py", line 394, in __init__
      |    errread, errwrite)
      |  File "c:\Python27\lib\subprocess.py", line 644, in _execute_child
      |    startupinfo)
      |WindowsError: [Error 2] The system cannot find the file specified
      |
22/02/16-17:04:11 fixPartFunc rmcBoot.imgRaw to make it rooted.
22/02/16-17:04:11   -- edit default.prop to change ro.secure to = 0
22/02/16-17:04:11   !! Can't find: rmcBootRamdisk/default.prop in C:\MC74\reviveMC74
  !! Rerun the 'fixPart' objective.
22/02/16-17:04:11 bunch(
  needed= [],
  replaceRecovery= True,
  checkFiles= True,
  adbMode= 'adb',
  error= []
)

22/02/16-17:04:19 revive===================================================================
22/02/16-17:04:19 --(reviveFunc)
22/02/16-17:04:19     (rmcBoot.img not found, calling fixPart to create it)
22/02/16-17:04:19 fixPartFunc rmcBoot.imgRaw to make it rooted.
22/02/16-17:04:19   -- edit default.prop to change ro.secure to = 0
22/02/16-17:04:19   !! Can't find: rmcBootRamdisk/default.prop in C:\MC74\reviveMC74
  !! Rerun the 'fixPart' objective.
22/02/16-17:04:19 {'needed': [], 'adbMode': None, 'error': []}

22/02/16-17:05:37 fixPart===================================================================
22/02/16-17:05:37 fixPartFunc rmcBoot.imgRaw to make it rooted.
22/02/16-17:05:37   -- edit default.prop to change ro.secure to = 0
22/02/16-17:05:37   !! Can't find: rmcBootRamdisk/default.prop in C:\MC74\reviveMC74
  !! Rerun the 'fixPart' objective.
22/02/16-17:05:37 {'needed': [], 'adbMode': None, 'error': []}

22/02/16-17:05:42 fixPart===================================================================
22/02/16-17:05:42 fixPartFunc rmcBoot.imgRaw to make it rooted.
22/02/16-17:05:42   -- edit default.prop to change ro.secure to = 0
22/02/16-17:05:42   !! Can't find: rmcBootRamdisk/default.prop in C:\MC74\reviveMC74
  !! Rerun the 'fixPart' objective.
22/02/16-17:05:42 {'needed': [], 'adbMode': None, 'error': []}

22/02/16-17:09:58 fixPart===================================================================
22/02/16-17:09:58 fixPartFunc rmcBoot.imgRaw to make it rooted.
22/02/16-17:09:58   -- edit default.prop to change ro.secure to = 0
22/02/16-17:09:58   !! Can't find: rmcBootRamdisk/default.prop in C:\MC74\reviveMC74
  !! Rerun the 'fixPart' objective.
22/02/16-17:09:58 {'needed': [], 'adbMode': None, 'error': []}

22/02/16-17:10:06 backupPart===================================================================
22/02/16-17:10:06     'adb devices'  (rc=0)
      |List of devices attached
      |Q2AT-CBD9-HX32	recovery
      |
22/02/16-17:10:06     'fastboot devices'  (rc=0)

22/02/16-17:10:06   --adbModeFunc, currentMode: recovery, targetMode: adb adb
22/02/16-17:10:06     'adb shell grep secure default.prop'  (rc=0)
      |ro.secure=0

22/02/16-17:10:06     'adb shell id'  (rc=0)
      |uid=0(root) gid=0(root)

22/02/16-17:10:06 backupPart boot partition: /dev/block/platform/sdhci.1/by-name/boot
22/02/16-17:10:06     'adb shell dd if=/dev/block/platform/sdhci.1/by-name/boot of=/cache/rmcBoot.imgRaw ibs=4096'  (rc=0)
      |2048+0 records in

      |16384+0 records out

      |8388608 bytes (8.0MB) copied, 0.262073 seconds, 30.5MB/s

22/02/16-17:10:08     'adb shell rm /cache/rmcBoot.imgRaw'  (rc=0)

22/02/16-17:10:08     'c:\Python27\python.exe installFiles/packBoot.py unpack rmcBoot.imgRaw'  (rc=0)
      |cwd C:\MC74\reviveMC74\rmcBootUnpack
      |packBoot exception: Traceback (most recent call last):
      |  File "installFiles/packBoot.py", line 202, in <module>
      |    unpack(biFn)
      |  File "installFiles/packBoot.py", line 30, in unpack
      |    resp, rc = execute("unpackbootimg -i ../"+biFn)
      |  File "C:\MC74\reviveMC74\ribou.py", line 375, in execute
      |    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      |  File "c:\Python27\lib\subprocess.py", line 394, in __init__
      |    errread, errwrite)
      |  File "c:\Python27\lib\subprocess.py", line 644, in _execute_child
      |    startupinfo)
      |WindowsError: [Error 2] The system cannot find the file specified
      |
22/02/16-17:10:08 {'needed': [], 'replaceRecovery': True, 'adbMode': 'adb', 'error': []}

22/02/16-17:12:06 fixPart===================================================================
22/02/16-17:12:06 fixPartFunc rmcBoot.imgRaw to make it rooted.
22/02/16-17:12:06   -- edit default.prop to change ro.secure to = 0
22/02/16-17:12:06   !! Can't find: rmcBootRamdisk/default.prop in C:\MC74\reviveMC74
  !! Rerun the 'fixPart' objective.
22/02/16-17:12:06 {'needed': [], 'adbMode': None, 'error': []}

22/02/16-17:12:08 fixPart===================================================================
22/02/16-17:12:08 fixPartFunc rmcBoot.imgRaw to make it rooted.
22/02/16-17:12:08   -- edit default.prop to change ro.secure to = 0
22/02/16-17:12:08   !! Can't find: rmcBootRamdisk/default.prop in C:\MC74\reviveMC74
  !! Rerun the 'fixPart' objective.
22/02/16-17:12:08 {'needed': [], 'adbMode': None, 'error': []}

22/02/16-17:12:09 fixPart===================================================================
22/02/16-17:12:09 fixPartFunc rmcBoot.imgRaw to make it rooted.
22/02/16-17:12:09   -- edit default.prop to change ro.secure to = 0
22/02/16-17:12:09   !! Can't find: rmcBootRamdisk/default.prop in C:\MC74\reviveMC74
  !! Rerun the 'fixPart' objective.
22/02/16-17:12:09 {'needed': [], 'adbMode': None, 'error': []}

22/02/16-17:12:10 fixPart===================================================================
22/02/16-17:12:10 fixPartFunc rmcBoot.imgRaw to make it rooted.
22/02/16-17:12:10   -- edit default.prop to change ro.secure to = 0
22/02/16-17:12:10   !! Can't find: rmcBootRamdisk/default.prop in C:\MC74\reviveMC74
  !! Rerun the 'fixPart' objective.
22/02/16-17:12:10 {'needed': [], 'adbMode': None, 'error': []}

**Comment by qwery26** [comment]
It appears that 'unpackbookimg.exe' is not in your PATH   (I don't know why the script didn't complain about that when it was first run.)

I don't know how much you know about computers or Windows.    Can you put the unpackbootimg.exe file in the installFiles directory into a directory in your PATH? 

First, in a command prompt, type:       unpackbootimg   
See if it complains that the file does exist.  If you have an old copy of that file in your PATH, (if you have the 'which' command,   'which unpackbootimg'   would tell you where the unpackbootimg.exe is.   Erase that one and copy the one from the installFiles directory into a directory in your PATH.   Then try the:   unpackbookimg
  command again to verify that it can be found and is executable.

If the unpackbootimg.exe command is found,   from the \mc74\revivemc74\rmcBootUnpack directory try this command:

    unpackbootimg -i ../rmcBoot.imgOrig

Hopefully that will unpack the img and you should see a bunch of files.

**Comment by neodataworks** [comment]
I did this and after a reboot, the unpackbootimg command is recognized but comes up with an error that it can not run properly because it is missing cygwin1.dll.  so i copied that file into the same location and that error when away but came up with another that says application is unable to start correctly.  i was only have to get the unpackbootimg command to run without error from within the reviveMC74 directory but it creates no additional files.

the which command shows that it is using /cmd/unpackbootimg which is the location that i put the one from the installfiles directory.

**Comment by qwery26** [comment]
Okay,  we need the unpackbootimg command to run from /mc74/reviveMC74/rmcBootUnpack

If the unpackbootimg.exe is in /cmd/ then, I think,  cyggcc_s-1.dll, and cygwin1.dll should also be in /cmd/

What is the error message when you try to` run:

    cd \mc74\revivemc74\rmcBootUnpack
    unpackbootimg -i ../rmcBoot.imgOrig

**Comment by neodataworks** [comment]
![image](https://user-images.githubusercontent.com/6485743/154500729-40e4e846-40c9-4008-844a-ad5b5dcd7396.png)

same error.  i did not have the cyggcc_s-1.dll on my system but i got it and copied to the same location and same error.  i have tried to replace the unpackbootimg program with a fresh copy and redownloaded from your git site and same error.  i am spinning up a linux box to see if i can run this unpack there.

**Comment by qwery26** [comment]
Hmm, that looks like a windows problem with wrong/bad  .dlls or .exe   Linux should be a good thing to try, but you will need to get the linux version of unpackbootimg  I don't recall where that comes from.

If the linux try doesn't work, I'll try sending the while unpackboot tools directory/zip to you.

I assume that all the tests you did in the cmd.exe screenshot you sent had the same Application Error  pop-up window error.  (You should not need to use: '..\unpackbootimg.exe'   If it is in the path correctly, just unpackbootimg should be okay.

**Comment by neodataworks** [comment]
this is correct, i get this error all of the time and i do not need to use the ..\ to run the command.  i just need to figure out how to pass my usb through to a linux VM or just move these files over to try and run the unpack.  if you have these to send, that would be greatly appreciated.
much thanks

**Comment by neodataworks** [comment]
I am looking at Linux option now and this may be beyond me. The
reviveMC74.py does not find programs that I know are there such as chmod,
gzip, etc.  I can type these without any other path and they work so I
don't know why the script says they are not there. The adb can run and sees
the phone but not through the script. And I can't find unpackbootimg for
Linux anywhere even though I have installed the android application pack
that is said to have it. If you have another version of this, please send
when you get the chance.

Thanks

**Comment by reviveMC74** [comment]
I put (what I think is all the stuff you need) into https://github.com/reviveMC74/imgTools,   So, clone that somewhere on your windows system.

For linux (and windows) reviveMC74.py has a **checkFiles** objective to see if all the files and program exist before continuing.    The list of needed programs is:

> neededProgs = bunch(  # These are commands that demonstrate that needed programs are in the
>    PATH and that they execute (ie not just the filename of the program
>   adb = ["adb version", "adbNeeded"],   
>   fastboot = ["fastboot", "adbNeeded"],
>   unpackbootimg = ["unpackbootimg", "unpNeeded"],
>   mkbootimg = ["mkbootimg", "unpNeeded"],
>   chmod = ["chmod", "unpNeeded"], 
>   cpio = ["cpio", "unpNeeded"], 
>   gzip = ["gzip -V", "gzipNeeded"], 
>   gunzip = ["gunzip -V", "gzipNeeded"], 
> )

To check the programs is just tries to execute them (to execute the first string in the neededPrograms element for each file):

> def chkProg(pg):
>   try:
>     resp, rc = execute(pg[0], False)
>   except:
>     progName = pg[0].split(' ')[0]
>     #print("Can't find '"+progName+"' program in path")
>     state.error.append("checkProgs: Can't find '"+progName+"' program")
>     state.needed.append(pg[1])
>     return False
>   return True

Could you show me the reviveMC74,log file from linux when you try the script (so I can see what it is complaining about for the allegedly missing programs?

**Comment by neodataworks** [comment]
so i think it got a bit further.  i can see files in the rmcBootUnpack but now the error was with cpio.exe and the RamDisk folder is empty.  below are the logs:


22/02/17-07:19:52 revive===================================================================
22/02/17-07:19:52 --(reviveFunc)
22/02/17-07:19:52     (rmcBoot.img not found, calling fixPart to create it)
22/02/17-07:19:52 fixPartFunc rmcBoot.imgRaw to make it rooted.
22/02/17-07:19:52   -- edit default.prop to change ro.secure to = 0
22/02/17-07:19:52   !! Can't find: rmcBootRamdisk/default.prop in C:\MC74\reviveMC74
  !! Rerun the 'fixPart' objective.
22/02/17-07:19:52 {'needed': [], 'adbMode': None, 'error': []}

22/02/17-20:15:54 revive===================================================================
22/02/17-20:15:54 --(reviveFunc)
22/02/17-20:15:54     (rmcBoot.img not found, calling fixPart to create it)
22/02/17-20:15:54 fixPartFunc rmcBoot.imgRaw to make it rooted.
22/02/17-20:15:54   -- edit default.prop to change ro.secure to = 0
22/02/17-20:15:54   !! Can't find: rmcBootRamdisk/default.prop in c:\MC74\reviveMC74
  !! Rerun the 'fixPart' objective.
22/02/17-20:15:54 {'needed': [], 'adbMode': None, 'error': []}

22/02/17-20:16:55 revive===================================================================
22/02/17-20:16:55 --(reviveFunc)
22/02/17-20:16:55     (rmcBoot.img not found, calling fixPart to create it)
22/02/17-20:16:55 fixPartFunc rmcBoot.imgRaw to make it rooted.
22/02/17-20:16:55   -- edit default.prop to change ro.secure to = 0
22/02/17-20:16:55   !! Can't find: rmcBootRamdisk/default.prop in c:\MC74\reviveMC74
  !! Rerun the 'fixPart' objective.
22/02/17-20:16:55 {'needed': [], 'adbMode': None, 'error': []}

22/02/17-20:17:22 revive===================================================================
22/02/17-20:17:22 --(reviveFunc)
22/02/17-20:17:22     (rmcBoot.img not found, calling fixPart to create it)
22/02/17-20:17:27     'adb devices'  (rc=0)
      |List of devices attached
      |* daemon not running. starting it now on port 5037 *
      |* daemon started successfully *
      |Q2AT-CBD9-HX32	recovery
      |
22/02/17-20:17:27     'fastboot devices'  (rc=0)

22/02/17-20:17:27   --adbModeFunc, currentMode: recovery, targetMode: adb adb
22/02/17-20:17:28     'adb shell grep secure default.prop'  (rc=0)
      |ro.secure=0

22/02/17-20:17:28     'adb shell id'  (rc=0)
      |uid=0(root) gid=0(root)

22/02/17-20:17:28 backupPart boot partition: /dev/block/platform/sdhci.1/by-name/boot
22/02/17-20:17:28     'adb shell dd if=/dev/block/platform/sdhci.1/by-name/boot of=/cache/rmcBoot.imgRaw ibs=4096'  (rc=0)
      |2048+0 records in

      |16384+0 records out

      |8388608 bytes (8.0MB) copied, 0.266532 seconds, 30.0MB/s

22/02/17-20:17:29     'adb shell rm /cache/rmcBoot.imgRaw'  (rc=0)

22/02/17-20:17:40     'C:\Python27\python.exe installFiles/packBoot.py unpack rmcBoot.imgRaw'  (rc=0)
      |cwd c:\MC74\reviveMC74\rmcBootUnpack
      |unpackbootimg rmcBoot.imgRaw: (rc=0) resp:
      |  |BOARD_KERNEL_CMDLINE console=ttyS0,115200n8 androidboot.console=ttyS0 mem=510M
      |  |BOARD_KERNEL_BASE a0000000
      |  |BOARD_NAME 
      |  |BOARD_PAGE_SIZE 2048
      |  |BOARD_HASH_TYPE sha1
      |  |BOARD_KERNEL_OFFSET 00008000
      |  |BOARD_RAMDISK_OFFSET 01000000
      |  |BOARD_SECOND_OFFSET 00f00000
      |  |BOARD_TAGS_OFFSET 00000100
      |  |BOARD_HEADER_VERSION 0
      |ls-unpack c:\MC74\reviveMC74\rmcBootUnpack:
      |--|./base
      |--|./board
      |--|./cmdline
      |--|./hash
      |--|./headerversion
      |--|./kerneloff
      |--|./pagesize
      |--|./ramdisk.gz
      |--|./ramdiskoff
      |--|./secondoff
      |--|./tagsoff
      |--|./zImage
      |gunzip ramdisk.gz: 0
      |
      |ramdisk 615680 bytes
      |cwd rd c:\MC74\reviveMC74\rmcBootRamdisk
      |cpio -i <ramdisk: -1073741701
      |
22/02/17-20:17:40 fixPartFunc rmcBoot.imgRaw to make it rooted.
22/02/17-20:17:40   -- edit default.prop to change ro.secure to = 0
22/02/17-20:17:40   !! Can't find: rmcBootRamdisk/default.prop in c:\MC74\reviveMC74
  !! Rerun the 'fixPart' objective.
22/02/17-20:17:40 {'needed': [], 'replaceRecovery': True, 'adbMode': 'adb', 'error': []}

22/02/17-20:18:05 revive===================================================================
22/02/17-20:18:05 --(reviveFunc)
22/02/17-20:18:05     (rmcBoot.img not found, calling fixPart to create it)
22/02/17-20:18:05 fixPartFunc rmcBoot.imgRaw to make it rooted.
22/02/17-20:18:05   -- edit default.prop to change ro.secure to = 0
22/02/17-20:18:05   !! Can't find: rmcBootRamdisk/default.prop in c:\MC74\reviveMC74
  !! Rerun the 'fixPart' objective.
22/02/17-20:18:05 {'needed': [], 'adbMode': None, 'error': []}

**Comment by neodataworks** [comment]
oh wait, cpio was in another location.  i deleted that along with all the other rmc files and it went through!!

i think i am good, will enter sip info and test.  thanks for all your help, you are better than most support out there.

**Comment by neodataworks** [comment]
One other question, have you been able to load other apk files to the
phone?  i tried to add the play store and another app that I use for my
Voip provider and i get an error from abd that says "/sbin/sh: pm: not
found".  i have tried the install to the sdcard as well as i do not know if
maybe there is not enough room to install these additional apps?

thanks for your help.

**Comment by reviveMC74** [comment]
I answered this question here: [https://www.reddit.com/r/ReviveMC74/comments/sz0c1y/adding_apps_to_the_mc74_no_playstore/](https://www.reddit.com/r/ReviveMC74/comments/sz0c1y/adding_apps_to_the_mc74_no_playstore/)  That's the place I'd prefer questions/discussion that is not directly related to bugs on the reviveMC74 script/process.
