### ISSUE TITLE
MacOS fastboot devices doesn't pick up MC74

### ISSUE THREAD

**Issue by kit-repo-depot** [reviveMC74/reviveMC74#22]
Once revivemc74.py executes `add reboot bootloader` when it loops through `fastboot devices` while it waits for the reboot, the MC74 never shows up as a device. 

Ran both as root and as regular user, with a 2021 MacBook Air M1 on MacOS 12.5

I suspect its some version of the fastboot driver issue from here https://github.com/reviveMC74/reviveMC74/blob/670cf5583cc068706dc2d57021a4e414cf2acf45/doc/fastbootDrivers.md?plain=1#L15 because the MC74 shows up in system information with device ID 0x0d02, and while it's in recovery mode adb recognizes it just fine. 

Here's my reviveMC74.log

```
22/09/03-19:50:21 revive===================================================================
22/09/03-19:50:21 --(reviveFunc)
22/09/03-19:50:21     (rmcBoot.img not found, calling fixPart to create it)
22/09/03-19:50:21     'adb devices'  (rc=0)
      |List of devices attached
      |
22/09/03-19:50:21     'fastboot devices'  (rc=0)

22/09/03-19:50:21   --adbModeFunc, currentMode: unknown, targetMode: adb
22/09/03-19:51:48     'adb devices'  (rc=0)
      |List of devices attached
      |Q2AT-67WH-T7ZP	recovery
      |
22/09/03-19:51:48     'adb shell grep secure default.prop'  (rc=0)
      |- exec '/system/bin/sh' failed: No such file or directory (2) -
22/09/03-19:51:48     'adb devices'  (rc=0)
      |List of devices attached
      |Q2AT-67WH-T7ZP	recovery
      |
22/09/03-19:51:48     'fastboot devices'  (rc=0)

22/09/03-19:51:48   --adbModeFunc, currentMode: recovery, targetMode: fastboot adb
22/09/03-19:51:49     'adb reboot bootloader'  (rc=0)

22/09/03-19:51:49     'fastboot devices'  (rc=0)

22/09/03-19:51:54     'fastboot devices'  (rc=0)

22/09/03-19:51:59     'fastboot devices'  (rc=0)

22/09/03-19:52:04     'fastboot devices'  (rc=0)

22/09/03-19:52:09     'fastboot devices'  (rc=0)

22/09/03-19:52:14     'fastboot devices'  (rc=0)

22/09/03-19:52:19     'fastboot devices'  (rc=0)

22/09/03-19:52:24     'fastboot devices'  (rc=0)

22/09/03-19:52:29     'fastboot devices'  (rc=0)

22/09/03-19:52:34     'fastboot devices'  (rc=0)

22/09/03-19:52:39     'fastboot devices'  (rc=0)

22/09/03-19:52:44     'fastboot devices'  (rc=0)

22/09/03-19:52:49 {'needed': [], 'adbMode': 'unknown', 'serialNo': 'Q2AT-67WH-T7ZP', 'error': []}
```

**Comment by reviveMC74** [comment]
I think you are on the right track with the observation that device ID 0x0d02 means that the MC74 is acting like a 'fastboot' usb device.  I've only tested the process with Windows and Linux (not Mac, which I think is BSD based Unix?).   

Can you manually get it into 'fastboot' mode and use the 'fastboot' program from a command line to **see what the response to the 'fastboot devices' command is?**  (If you can get into ADB/recovery mode, the command:   'adb reboot bootloader' should get into fastbboot mode)  What is the response to 'fastboot devices' ??  

Aside from Mac's USB device driver for the PID 0x0d02 device, the 'fastboot' command on Mac could be the culprit.   (The other culprit could be the fastboot code on the MC74 side, but I don't think that is likely.)  On Linux this seems to need to be done as root (which you mention that you tried)

This error seems to be very early in the process, when the script is trying to flash the recovery partition.

**Comment by kit-repo-depot** [comment]
`fastboot devices` gives no response, only a new line; interestingly the `adb devices` command also gives no response at this stage. Like
```
% adb devices
List of devices attached
Q2AT-67WH-T7ZP	recovery

% adb reboot bootloader
% sudo fastboot devices
Password:
%
```

I tried `sudo fastboot devices` but I wonder if the Mac sudo isn't really giving fastboot the access it needs... I tried running on a windows VM but it didn't seem to recognize the USB. 

I'll try running from a raspberry pi or something to get the USB to recognize the device

**Comment by kit-repo-depot** [comment]
Running from a raspberry pi worked beautifully! Thank you

Do we want to continue to investigate the macOS issues? I'd be more than happy to help figure out what's going on with some direction

**Comment by reviveMC74** [comment]
I don't know how to debug a problem like this, on a Mac.  The approach I'd take is to use some tool like wireshark to monitor the communication over USB between the Mac and the MC74 when the 'fastboot devices' command was executed to see what communication is going on between the two devices (did the Max ask the MC74 about devices?  Did the MC74 respond?    On the PC, the problem is probably in the USB device driver for the PID 0x0d02 device.  Is there some better version of that device driver for the Mac (Mac OS is based on BSD or FreeBSD isn't it?)

In any event I'd say: No, let's let this issue drop.
