### ISSUE TITLE
checkFiles not picking up PATH correctly

### ISSUE THREAD

**Issue by benji-lewis** [reviveMC74/reviveMC74#23]
I am running through the objectives. I have added all required files to both PATH and the file that the python script is in and neither is running correctly. 

![image](https://user-images.githubusercontent.com/8136412/208429714-b4df1372-51be-4171-8f38-525f9697b623.png)

**Comment by benji-lewis** [comment]
Ran with python 2.7 instead of 3 and it has now worked

**Comment by qwery26** [comment]
The script, reviveMC74.py should work on python 2.7 or  python 3.x     If you want to help debug it, run python 2.7 and type the following:

from ribou import *
execute("adb version", False)

It should return a tuple with a str and and int.  What is the result?  Is there an exception?
