### ISSUE TITLE
fixPart fails Can't find file 'rmcBoot.img' after packBoot returned.

### ISSUE THREAD

**Issue by benji-lewis** [reviveMC74/reviveMC74#24]
The phone succesfully gets into ClockWork but I cannot get any further

`C:\Temp\revive3\reviveMC74>C:/python27/python.exe reviveMC74.py backupPart
backupPart Function:
    Executing: 'adb devices'
    'adb devices'  (rc=0)
      |List of devices attached
      |Q2AT-VNCR-Y4UM   recovery
      |
    Executing: 'fastboot devices'
    'fastboot devices'  (rc=0)

  --adbModeFunc, currentMode: recovery, targetMode: adb adb
    Executing: 'adb shell grep secure default.prop'
    'adb shell grep secure default.prop'  (rc=0)
      |ro.secure=0
    Executing: 'adb shell id'
    'adb shell id'  (rc=0)
      |uid=0(root) gid=0(root)
backupPart boot partition: /dev/block/platform/sdhci.1/by-name/boot
    Executing: 'adb shell dd if=/dev/block/platform/sdhci.1/by-name/boot of=/cache/rmcBoot.imgRaw ibs=4096'
    'adb shell dd if=/dev/block/platform/sdhci.1/by-name/boot of=/cache/rmcBoot.imgRaw ibs=4096'  (rc=0)
      |2048+0 records in
      |16384+0 records out
      |8388608 bytes (8.0MB) copied, 0.262858 seconds, 30.4MB/s
    Executing: 'adb shell rm /cache/rmcBoot.imgRaw'
    'adb shell rm /cache/rmcBoot.imgRaw'  (rc=0)

  --unpack rmcBoot.imgRaw and unpack the ramdisk
    Executing: 'C:\python27\python.exe installFiles/packBoot.py unpack rmcBoot.imgRaw'
    'C:\python27\python.exe installFiles/packBoot.py unpack rmcBoot.imgRaw'  (rc=0)
      |cwd C:\Temp\revive3\reviveMC74\rmcBootUnpack
      |unpackbootimg rmcBoot.imgRaw: (rc=0) resp:
      |  |BOARD_KERNEL_CMDLINE console=ttyS0,115200n8 androidboot.console=ttyS0 mem=510M
      |  |BOARD_KERNEL_BASE a0000000
      |  |BOARD_PAGE_SIZE 2048
      |ls-unpack C:\Temp\revive3\reviveMC74\rmcBootUnpack:
      |--|./base
      |--|./cmdline
      |--|./pagesize
      |--|./ramdisk.gz
      |--|./zImage
      |gunzip ramdisk.gz: 0
      |
      |ramdisk 616704 bytes
      |executeErr: 1205 blocks
      |
      |cwd rd C:\Temp\revive3\reviveMC74\rmcBootRamdisk
      |executeErr: cpio: charger: Function not implemented
      |cpio: default.prop: Function not implemented
      |cpio: fstab.capri_me1: Function not implemented
      |cpio: init: Function not implemented
      |cpio: init.bcm911130_me1.rc: Function not implemented
      |cpio: init.brcm.usb.rc: Function not implemented
      |cpio: init.common.rc: Function not implemented
      |cpio: init.goldfish.rc: Function not implemented
      |cpio: init.log.rc: Function not implemented
      |cpio: init.rc: Function not implemented
      |cpio: init.trace.rc: Function not implemented
      |cpio: init.usb.rc: Function not implemented
      |cpio: res/images/charger/battery_0.png: Function not implemented
      |cpio: res/images/charger/battery_1.png: Function not implemented
      |cpio: res/images/charger/battery_2.png: Function not implemented
      |cpio: res/images/charger/battery_3.png: Function not implemented
      |cpio: res/images/charger/battery_4.png: Function not implemented
      |cpio: res/images/charger/battery_5.png: Function not implemented
      |cpio: res/images/charger/battery_charge.png: Function not implemented
      |cpio: res/images/charger/battery_fail.png: Function not implemented
      |cpio: sbin/adbd: Function not implemented
      |cpio: ueventd.bcm911130_me1.rc: Function not implemented
      |cpio: ueventd.goldfish.rc: Function not implemented
      |cpio: ueventd.rc: Function not implemented
      |1205 blocks
      |
      |cpio -i <ramdisk: 0
      |
Acheived objective 'backupPart'

C:\Temp\revive3\reviveMC74>C:/python27/python.exe reviveMC74.py fixPart
fixPart Function:
fixPartFunc rmcBoot.imgRaw to make it rooted.
  -- edit default.prop to change ro.secure to = 0
    Executing: 'chmod go-w rmcBootRamdisk/default.prop'
    'chmod go-w rmcBootRamdisk/default.prop'  (rc=0)

  -- editFile rmcBootRamdisk/init.rc find 'symlink /system/etc'
    firstInsert '    symlink /storage/emulated/legacy/ssm /ssm'
    next line   '    symlink /sys/kernel/debug /d' (True True)
  -- repack ramdisk, repack rmcBoot.img
    Executing: 'C:\python27\python.exe installFiles/packBoot.py pack rmcBoot.img'
    'C:\python27\python.exe installFiles/packBoot.py pack rmcBoot.img'  (rc=0)
      |pack: rmcBoot.img
      |  cwd rd C:\Temp\revive3\reviveMC74\rmcBootRamdisk
      |'charger\ndata\ndefault.prop\ndev\nfstab.capri_me1\ninit\ninit.bcm911130_me1.rc\ninit.brcm.usb.rc\ninit.common.rc\ninit.goldfish.rc\ninit.log.rc\ninit.rc\ninit.trace.rc\ninit.usb.rc\nproc\nres\nres/images\nres/images/charger\nres/images/charger/battery_0.png\nres/images/charger/battery_1.png\nres/images/charger/battery_2.png\nres/images/charger/battery_3.png\nres/images/charger/battery_4.png\nres/images/charger/battery_5.png\nres/images/charger/battery_charge.png\nres/images/charger/battery_fail.png\nsbin\nsbin/adbd\nsbin/ueventd.lnk\nsbin/watchdogd.lnk\nsys\nsystem\nueventd.bcm911130_me1.rc\nueventd.goldfish.rc\nueventd.rc\n'
      |cpio -o  rc=2, 616704 bytes
      |ls-pack C:\Temp\revive3\reviveMC74\rmcBootUnpack:
      |--|C:\Temp\revive3\reviveMC74\rmcBootUnpack/base
      |--|C:\Temp\revive3\reviveMC74\rmcBootUnpack/cmdline
      |--|C:\Temp\revive3\reviveMC74\rmcBootUnpack/pagesize
      |--|C:\Temp\revive3\reviveMC74\rmcBootUnpack/ramdisk
      |--|C:\Temp\revive3\reviveMC74\rmcBootUnpack/zImage
      | ramdisk gzipped 0
      |cmd: '['mkbootimg', '--kernel', 'zImage', '--ramdisk', 'ramdisk.gz', '--cmdline', 'console=ttyS0,115200n8 androidboot.console=ttyS0 mem=510M', '--base', '0xa0000000', '--pagesize', '2048', '--output', '../rmcBoot.img2212191723']'
      |(rc=1) resp:
      |  |error: could not load kernel 'zImage'
fixPart failed:
  --fixPart: Can't find file 'rmcBoot.img' after packBoot returned.

C:\Temp\revive3\reviveMC74>C:/python27/python.exe reviveMC74.py fixPart
fixPart Function:
fixPartFunc rmcBoot.imgRaw to make it rooted.
  -- edit default.prop to change ro.secure to = 0
    Executing: 'chmod go-w rmcBootRamdisk/default.prop'
    'chmod go-w rmcBootRamdisk/default.prop'  (rc=0)

  -- editFile rmcBootRamdisk/init.rc find 'symlink /system/etc'
    firstInsert '    symlink /storage/emulated/legacy/ssm /ssm'
    next line   '    symlink /storage/emulated/legacy/ssm /ssm' (True False)
  (ignoring duplicate insertion edit request for: '    symlink /storage/emulated/legacy/ssm /ssm'
  -- repack ramdisk, repack rmcBoot.img
    Executing: 'C:\python27\python.exe installFiles/packBoot.py pack rmcBoot.img'

    'C:\python27\python.exe installFiles/packBoot.py pack rmcBoot.img'  (rc=0)
      |pack: rmcBoot.img
      |  cwd rd C:\Temp\revive3\reviveMC74\rmcBootRamdisk
      |'charger\ndata\ndefault.prop\ndev\nfstab.capri_me1\ninit\ninit.bcm911130_me1.rc\ninit.brcm.usb.rc\ninit.common.rc\ninit.goldfish.rc\ninit.log.rc\ninit.rc\ninit.trace.rc\ninit.usb.rc\nproc\nres\nres/images\nres/images/charger\nres/images/charger/battery_0.png\nres/images/charger/battery_1.png\nres/images/charger/battery_2.png\nres/images/charger/battery_3.png\nres/images/charger/battery_4.png\nres/images/charger/battery_5.png\nres/images/charger/battery_charge.png\nres/images/charger/battery_fail.png\nsbin\nsbin/adbd\nsbin/ueventd.lnk\nsbin/watchdogd.lnk\nsys\nsystem\nueventd.bcm911130_me1.rc\nueventd.goldfish.rc\nueventd.rc\n'
      |cpio -o  rc=2, 616704 bytes
      |ls-pack C:\Temp\revive3\reviveMC74\rmcBootUnpack:
      |--|C:\Temp\revive3\reviveMC74\rmcBootUnpack/base
      |--|C:\Temp\revive3\reviveMC74\rmcBootUnpack/cmdline
      |--|C:\Temp\revive3\reviveMC74\rmcBootUnpack/pagesize
      |--|C:\Temp\revive3\reviveMC74\rmcBootUnpack/ramdisk
      |--|C:\Temp\revive3\reviveMC74\rmcBootUnpack/ramdisk.gz
      |--|C:\Temp\revive3\reviveMC74\rmcBootUnpack/zImage
      | ramdisk gzipped 2
      |cmd: '['mkbootimg', '--kernel', 'zImage', '--ramdisk', 'ramdisk.gz', '--cmdline', 'console=ttyS0,115200n8 androidboot.console=ttyS0 mem=510M', '--base', '0xa0000000', '--pagesize', '2048', '--output', '../rmcBoot.img2212191724']'
      |(rc=1) resp:
      |  |error: could not load kernel 'zImage'
fixPart failed:
  --fixPart: Can't find file 'rmcBoot.img' after packBoot returned.`

**Comment by qwery26** [comment]
It looks like 'pack' could not find the kernel image ('zImage') file in \Temp\revive3\reviveMC74\rmcBootUnpack     Look in the rmcBootUnpack directory (or other directories under \Temp\revive3) can you see any file that 'looks like' a kernel image, (zImage, zImage.gz, kernelXXX, kernel.gz  ??)

What is the 'version' of  'unpackbootimg.exe'  and 'mkbootimg.exe' in your path?

**Comment by qwery26** [comment]
(I think this issue is resolved by using the updated version of unpackbootimage.exe and mkbootimg.exe)
