### ISSUE TITLE
Revival process 

### ISSUE THREAD

**Issue by BillBallong** [reviveMC74/reviveMC74#25]
23/12/23-21:40:19 revive===================================================================
23/12/23-21:40:19 --(reviveFunc)
23/12/23-21:40:19     'adb shell mount /data'  (rc=0)
      |- exec '/system/bin/sh' failed: No such file or directory (2) -
23/12/23-21:40:19   flashPartFunc, writing rmcBoot.img to /dev/block/platform/sdhci.1/by-name/boot
23/12/23-21:40:19     'adb push rmcBoot.img /cache/rmcBoot.img'  (rc=1)
      |[  1%] /cache/rmcBoot.img
      |[  2%] /cache/rmcBoot.img
      |[  4%] /cache/rmcBoot.img
      |[  5%] /cache/rmcBoot.img
      |[  7%] /cache/rmcBoot.img
      |[  8%] /cache/rmcBoot.img
      |[  9%] /cache/rmcBoot.img
      |[ 11%] /cache/rmcBoot.img
      |[ 12%] /cache/rmcBoot.img
      |[ 14%] /cache/rmcBoot.img
      |[ 15%] /cache/rmcBoot.img
      |[ 17%] /cache/rmcBoot.img
      |[ 18%] /cache/rmcBoot.img
      |[ 19%] /cache/rmcBoot.img
      |[ 21%] /cache/rmcBoot.img
      |[ 22%] /cache/rmcBoot.img
      |[ 24%] /cache/rmcBoot.img
      |adb: error: failed to copy 'rmcBoot.img' to '/cache/rmcBoot.img': remote Permission denied
      |rmcBoot.img: 0 files pushed. 171.9 MB/s (1179648 bytes in 0.007s)
23/12/23-21:40:19 {'needed': [], 'adbMode': None, 'error': ['Writing rmcBoot.img on device failed']}

:~/reviveMC74-main$ adb devices
List of devices attached
Q2AT-QXYJ-YSVE  recovery

**Comment by qwery26** [comment]
Hmm, it looks like 'adb push' can't copy all of rmcBoot.img to the /cache directory, (it seems to have copied some of the file, even though it says 'remote Premission denied')  Can you open and 'adb shell' on the device and see how much space there is in /cache (and that it is r/w (and that you are 'root' when 'adb' shell is running?

**Comment by BillBallong** [comment]
Looks like there was 0 files pushed, so it looks like there isn't any files going over to the device. When I boot the device into recovery there is a dead android robot logo. I have done the revival process on 1 MC74, but the 3 others I have only boots into dead recovery. 

Running 'adb shell' gives me "- exec '/system/bin/sh' failed: No such file or directory (2) -"

**Comment by qwery26** [comment]
I'm confused about the state and history of the MC74 you are reviving.  To
get to the state (ffixBootFunc) I think the MC74 had to execute some 'adb
shell' commands (ie in the BackupBootPartitionFunc phase)  (Assuming you
know some python, look in reviveMc74.py, line 232 for backupBootFunc and
line 266 for fixBootPartitionFunc.  Line 244 of backupBootFunc does an 'adb
shell rm /cache/rmcBoot.img', so unless that failed, the shell command
should work.)

I think you said that on revive worked succeeded (to the end where
applications where installed?)   Did the subsequent 3 installs fail?
 Could it be that there is some 'state' left over from the first install
that confused the subsequent installs?  I don't tihink that is likely.

I assume we are talking about one of the 3 'dead recovery' machines.     It
seems that the recovery partition was not installed successfully.  Let's
retry that.
Try the command:
  python reviveMc74.py replaceRecovery

What will run the code at line 176 of reviveMc74.py   If the recovery
partition is not already setup, it should put you in 'fastboot' mode and
flash the recovery partition.
Send me the console output or the log file for that.

**Comment by qwery26** [comment]
Oops, I referenced the wrong line numbers in reviveMC74.py   ignore those,
look for the lines that contain 'def fixBoorFunc"  and 'def
backupBootFunc:' etc.

**Comment by BillBallong** [comment]
It looks like when running 'python reviveMC74.py replaceRecovery' it forces the action to replace recovery, and after this is finished I can run 'python reviveMc74.py' and complete the revive with no problem. Problem solved I guess.

**Comment by qwery26** [comment]
I wonder if reviveMC74.py got confused about the state of the recovery process because you here using it on several MC74s at once.   Okay, we'll call it solved for now.
