### ISSUE TITLE
global name 'fixBootPart' is not defined

### ISSUE THREAD

**Issue by k0derz-alex** [reviveMC74/reviveMC74#5]
Exception at <module>:584: NameError("global name 'fixBootPart' is not defined",)
 0  <module> 585 reviveMc74.py --
 1  reviveMain 147 reviveMc74.py --
 2  fixPartFunc 321 reviveMc74.py --
  Locals: imgFn, partName, partFid
Explore exception stk:
ex> qui
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'qui' is not defined
ex> quit
Use quit() or Ctrl-D (i.e. EOF) to exit
ex>

**Comment by reviveMC74** [comment]
Should be fixed now.  (get pull and retry)
