### ISSUE TITLE
Script failing at ADB Reboot (InstallApps)

### ISSUE THREAD

**Issue by PhoenixSheppy** [reviveMC74/reviveMC74#7]
So I ran the script, acted funky at the backup part, kept going and started over. Got to the "InstallApps" Portion and it attempts to reboot from recovery and it just hangs there. Not sure where to go from here.

![image](https://user-images.githubusercontent.com/20131900/97817996-606d9100-1c65-11eb-981e-54aa999cce5b.png)

(Error from earlier)
![image](https://user-images.githubusercontent.com/20131900/97818004-711e0700-1c65-11eb-8746-524efd2926e3.png)

This is on Windows 10, w/ Python 2.7

**Comment by reviveMC74** [comment]
The second screen shows that the 'adb shell dd if=....' command failed with an rc=-1, but no error message.  This seems to be after the 'fastboot reboot'  I'll have to do something that shows the state MC74 and the adb connection at that time.

Sounds as though you manually got past this issue so you may not be able to or interested in retrying this.  I'll put in some more stuff to try to see what the state is at that time.

In your other comments you mentioned additions to build.prop.  I think the script does the persist.meraki.usb_debug=1    change as you do.   I like the addition of 'mtp,' to the persist.sys.usb.config.

 What do  persist.service.adb.enable=1  and persist.service.debuggable=1 do?    (adb seems to be running without it, does service.debuggable do something additional?   I look at the   system/core/init/init.c  and system/core/property_service.c code to try to figure out what some of the propeties  do, but I don't know what those do)

**Comment by PhoenixSheppy** [comment]
> The second screen shows that the 'adb shell dd if=....' command failed with an rc=-1, but no error message.  This seems to be after the 'fastboot reboot'  I'll have to do something that shows the state MC74 and the adb connection at that time.
> 
> Sounds as though you manually got past this issue so you may not be able to or interested in retrying this.  I'll put in some more stuff to try to see what the state is at that time.
> 
> In your other comments you mentioned additions to build.prop.  I think the script does the persist.meraki.usb_debug=1    change as you do.   I like the addition of 'mtp,' to the persist.sys.usb.config.
> 
>  What do  persist.service.adb.enable=1  and persist.service.debuggable=1 do?    (adb seems to be running without it, does service.debuggable do something additional?   I look at the   system/core/init/init.c  and system/core/property_service.c code to try to figure out what some of the propeties  do, but I don't know what those do)
> 
> 

`persist.service.adb.enable` and `persist.service.debuggable` force the adb debugging tickbox under developer settings to be on / enabled.

I found that in an online guide, and it worked to get debugging enabled. I currently have the phone setup to boot straight into Nova launcher. But I'd ideally like to be able to use the systemUI like a standard android tablet. Not sure how to restore the notification bar and softkeys.

**Comment by ra-alex** [comment]
# python reviveMc74.py installApps
  installApps Function:
  Executing: 'adb devices'
  'adb devices'  (rc=0)
    |List of devices attached
    |Q2AT-NE5S-NHXH     recovery
    |
  Executing: 'fastboot devices'
  'fastboot devices'  (rc=0)


  --adbModeFunc, currentMode: adb, targetMode: normal
    --Changing from adb mode to normal device mode
  Executing: 'adb reboot'

**And don't do it anythink**

**Comment by ra-alex** [comment]
executing the script commands via console it keeps showing me that /data has no space ...

how did they solve that?

**Comment by reviveMC74** [comment]
(I'm copying/moving this information to https://www.reddit.com/r/ReviveMC74/ to make it more usable to other people and to not confuse my by having open 'issues' on github)

If you can boot the device normally (ie not into recovery mode) and you can get 'adb shell' to work (and you know unix)... The /data and /system partitions should be mounted normally.   Try this:

> phone / # mount |grep sd
/dev/block/platform/sdhci.1/by-name/system /system ext4 rw,relatime,user_xattr,acl,barrier=1,data=ordered 0 0
/dev/block/platform/sdhci.1/by-name/userdata /data ext4 rw,nosuid,nodev,noatime,errors=panic,user_xattr,acl,barrier=1,data=ordered,noauto_da_alloc 0 0
/dev/block/platform/sdhci.1/by-name/cache /cache ext4 rw,nosuid,noatime,errors=panic,user_xattr,acl,barrier=1,data=ordered 0 0
phone / # df
Filesystem             Size   Used   Free   Blksize
/dev                   247M    32K   247M   4096
/system                498M   185M   312M   4096
/data                  956M   160M   796M   4096
/cache                1015M   641M   373M   4096
/mnt/secure            247M     0K   247M   4096
/mnt/asec              247M     0K   247M   4096
/mnt/obb               247M     0K   247M   4096
/tmp                   247M     0K   247M   4096
/mnt/shell/emulated    956M   160M   796M   4096

The 'mount' commands shows that /data is mounted from the  'userdata' partition of the sdhci.1 device
The 'df' command shows that II have 796 MB left on /data   (and 373 MB on /cache


If you can only get into  recovery mode, you need to mount:
 
> mount /dev/block/platform/sdhci.1/by-name/userdata /data

the userdata partition over /data  (I think that is the right command.  Then you can do the 'df' command.

**Comment by ra-alex** [comment]
No you wrong ...

Indeed when starting normally I can see the partitioning:

# adb shell
e0-55-3d-4f-6e-2f-meraki-admin-network-wir / # df
Filesystem             Size   Used   Free   Blksize
/dev                   247M    32K   247M   4096
/system                498M   185M   312M   4096
/data                  956M   955M     1M   4096
/cache                1015M   641M   374M   4096
/mnt/secure            247M     0K   247M   4096
/mnt/asec              247M     0K   247M   4096
/mnt/obb               247M     0K   247M   4096
/tmp                   247M     0K   247M   4096
/mnt/shell/emulated    956M   955M     1M   4096

but still it remains the same!

**Comment by ra-alex** [comment]
My mistake

I just found in a backup folder 800 mb approx, when I deleted its content the project passed without problems!

Wooohooooo !!! now how software use to IP Phone!
