### ISSUE TITLE
import error, no module 

### ISSUE THREAD

**Issue by ra-alex** [reviveMC74/reviveMC74#8]
|[100%] /cache/rmcBoot.img
    |/cache/rmcBoot.img: 1 file pulled. 6.8 MB/s (8388608 bytes in 1.174s)
  Executing: 'adb shell rm /cache/rmcBoot.img'
  'adb shell rm /cache/rmcBoot.img'  (rc=0)

    -- unpack rmcBoot.img and unpack the ramdisk
  Executing: 'python installFiles/packBoot.py unpack rmcBoot.img'
**executeErr: Traceback (most recent call last):
  File "installFiles/packBoot.py", line 7, in <module>
    from ribou import *
ImportError: No module named ribou**

  'python installFiles/packBoot.py unpack rmcBoot.img'  (rc=1)

Acheived objective 'backupPart'

**Comment by qwery26** [comment]
Hmm.  the file  ribou.py should be in the directory you are working from (usually called 'reviveMC74' )  that file should be in the directory that also contains 'reviveMC74.py'    Is ribou.py there?  If so, there must be something about the paths python is looking for things in.  What does:     echo %PYTHONPATH%     return?

If you do have   ribou.py     copy it to the 'installFiles'  directory and try again.

**Comment by ra-alex** [comment]
Thank you

I know what I have to do but I'm not uploading code to the repository, the idea is to contribute to be corrected by the maintainers and collaborators!

Now ...

fixPart error in command :

    | ramdisk gzipped 0
    |cmd: 'mkbootimg --kernel rmcBoot.img-zImage --ramdisk rmcBoot.img-ramdisk.gz --cmdline 'console=ttyS0,115200n8 androidboot.console=ttyS0 mem=510M' --base a0000000 --pagesize 2048 --output ../rmcBoot.img2011021758'
    |executeErr: usage: mkbootimg [-h] --kernel KERNEL [--ramdisk RAMDISK] [--second SECOND]
    |                 [--cmdline CMDLINE] [--base BASE]
    |                 [--kernel_offset KERNEL_OFFSET]
    |                 [--ramdisk_offset RAMDISK_OFFSET]
    |                 [--second_offset SECOND_OFFSET] [--os_version OS_VERSION]
    |                 [--os_patch_level OS_PATCH_LEVEL] [--tags_offset TAGS_OFFSET]
    |                 [--board BOARD] [--pagesize {2048,4096,8192,16384}] [--id] -o
    |                 OUTPUT
    |mkbootimg: error: argument --base: invalid parse_int value: 'a0000000'
    |
  -- write new rmcBoot.img to boot parition
  Executing: 'adb push rmcBoot.img /cache/rmcBoot.img'
  'adb push rmcBoot.img /cache/rmcBoot.img'  (rc=1)
    |adb: error: cannot stat 'rmcBoot.img': No such file or directory
  Executing: 'adb shell dd if=/cache/rmcBoot.img of=/dev/block/platform/sdhci.1/by-name/boot ibs=4096'
  'adb shell dd if=/cache/rmcBoot.img of=/dev/block/platform/sdhci.1/by-name/boot ibs=4096'  (rc=0)
    |dd: can't open '/cache/rmcBoot.img': No such file or directory
  Executing: 'adb shell rm /cache/rmcBoot.img'
  'adb shell rm /cache/rmcBoot.img'  (rc=0)
    |rm: can't remove '/cache/rmcBoot.img': No such file or directory
Acheived objective 'fixPart'

**Comment by qwery26** [comment]
This seems like a different error.  Did you (temporarily) fix the original error by copying ribou.py to installFiles??  Then you tried again and got this error?

You know what to do?  Oh good.  What?  Do I need to prefix the value of --base with '0x'?  I'm confused why you are seeing this error while I'm not seeing it. I have --base a000000  I'm sure it works for me.

Could we have different versions of mkbootimg.exe?    There is no --version number in it, but mine is 57465 bytes long. 

Could you try changing line 103 of installFiles/packBoot.py:
  cmd = "mkbootimg --kernel "+biFn+"-zImage --ramdisk "+biFn+"-ramdisk.gz" \
    +" --cmdline '"+cmdline+"' --base "+base+" --pagesize "+pagesize \
    +" --output ../"+biFn+ts
 
to

  cmd = "mkbootimg --kernel "+biFn+"-zImage --ramdisk "+biFn+"-ramdisk.gz" \
    +" --cmdline '"+cmdline+"' --base 0x"+base+" --pagesize "+pagesize \
    +" --output ../"+biFn+ts

(adding the '0x' after --base?    See if that fixes it for you.  -- then I will see if it breaks it for my version)

**Comment by qwery26** [comment]
Fixed the problem where 'import ribou.py' was not found.  (made packBoot.py add the cwd to sys.path, so it would find ribou.py)

Fixed execute() to return an ascii string whether in python2 or python3. 

Fixed packBoot.py not to hang if there is a exception (the handy dandy 'hndExcept()' which allows the user to debug exceptions, put up a console read that caused packBoot.py not to return, and reviveMC74.py to hang.

(This does not address the issue of weather mkbootimg --base requires a '0x' before the hex address (a0000000)  -- hopefully ra-alex will test that and tell me if he is using some different version of mkbootimg.exe)
